/**
 * Common 5-field cron expressions.
 * Adapted from NestJS/schedule — 6-field (seconds-based) entries removed.
 */
export enum CronExpression {
  EVERY_MINUTE = '* * * * *',
  EVERY_5_MINUTES = '*/5 * * * *',
  EVERY_10_MINUTES = '*/10 * * * *',
  EVERY_30_MINUTES = '*/30 * * * *',
  EVERY_HOUR = '0 * * * *',
  EVERY_2_HOURS = '0 */2 * * *',
  EVERY_3_HOURS = '0 */3 * * *',
  EVERY_4_HOURS = '0 */4 * * *',
  EVERY_5_HOURS = '0 */5 * * *',
  EVERY_6_HOURS = '0 */6 * * *',
  EVERY_7_HOURS = '0 */7 * * *',
  EVERY_8_HOURS = '0 */8 * * *',
  EVERY_9_HOURS = '0 */9 * * *',
  EVERY_10_HOURS = '0 */10 * * *',
  EVERY_11_HOURS = '0 */11 * * *',
  EVERY_12_HOURS = '0 */12 * * *',
  EVERY_DAY_AT_1AM = '0 1 * * *',
  EVERY_DAY_AT_2AM = '0 2 * * *',
  EVERY_DAY_AT_3AM = '0 3 * * *',
  EVERY_DAY_AT_4AM = '0 4 * * *',
  EVERY_DAY_AT_5AM = '0 5 * * *',
  EVERY_DAY_AT_6AM = '0 6 * * *',
  EVERY_DAY_AT_7AM = '0 7 * * *',
  EVERY_DAY_AT_8AM = '0 8 * * *',
  EVERY_DAY_AT_9AM = '0 9 * * *',
  EVERY_DAY_AT_10AM = '0 10 * * *',
  EVERY_DAY_AT_11AM = '0 11 * * *',
  EVERY_DAY_AT_NOON = '0 12 * * *',
  EVERY_DAY_AT_1PM = '0 13 * * *',
  EVERY_DAY_AT_2PM = '0 14 * * *',
  EVERY_DAY_AT_3PM = '0 15 * * *',
  EVERY_DAY_AT_4PM = '0 16 * * *',
  EVERY_DAY_AT_5PM = '0 17 * * *',
  EVERY_DAY_AT_6PM = '0 18 * * *',
  EVERY_DAY_AT_7PM = '0 19 * * *',
  EVERY_DAY_AT_8PM = '0 20 * * *',
  EVERY_DAY_AT_9PM = '0 21 * * *',
  EVERY_DAY_AT_10PM = '0 22 * * *',
  EVERY_DAY_AT_11PM = '0 23 * * *',
  EVERY_DAY_AT_MIDNIGHT = '0 0 * * *',
  EVERY_WEEK = '0 0 * * 0',
  EVERY_WEEKDAY = '0 0 * * 1-5',
  EVERY_WEEKEND = '0 0 * * 6,0',
  EVERY_1ST_DAY_OF_MONTH_AT_MIDNIGHT = '0 0 1 * *',
  EVERY_1ST_DAY_OF_MONTH_AT_NOON = '0 12 1 * *',
  EVERY_2ND_MONTH = '0 0 1 */2 *',
  EVERY_QUARTER = '0 0 1 */3 *',
  EVERY_6_MONTHS = '0 0 1 */6 *',
  EVERY_YEAR = '0 0 1 1 *',
}
