import type { RouteDefinition } from '@framework/http/types.js'
import { Tags } from '@framework/http/types.js'
import * as fulfillmentSetByIdRoutes from './[id]/route.js'
import * as geoZoneRoutes from './[id]/service-zones/[zoneId]/geo-zones/route.js'
import * as serviceZoneByIdRoutes from './[id]/service-zones/[zoneId]/route.js'
import * as serviceZoneRoutes from './[id]/service-zones/route.js'
import * as fulfillmentSetRoutes from './route.js'

export default [
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets',
    handler: fulfillmentSetRoutes.GET,
    operationId: 'listAdminFulfillmentSets',
    summary: 'List fulfillment sets',
    tags: [Tags.FULFILLMENT_SETS],
    output: fulfillmentSetRoutes.GetOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets',
    handler: fulfillmentSetRoutes.POST,
    input: fulfillmentSetRoutes.PostInput,
    operationId: 'createAdminFulfillmentSet',
    summary: 'Create a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
    output: fulfillmentSetRoutes.PostOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets/:id',
    handler: fulfillmentSetByIdRoutes.GET,
    input: fulfillmentSetByIdRoutes.GetInput,
    operationId: 'getAdminFulfillmentSet',
    summary: 'Retrieve a fulfillment set with service zones',
    tags: [Tags.FULFILLMENT_SETS],
    output: fulfillmentSetByIdRoutes.GetOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id',
    handler: fulfillmentSetByIdRoutes.POST,
    input: fulfillmentSetByIdRoutes.PostInput,
    operationId: 'updateAdminFulfillmentSet',
    summary: 'Update a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
    output: fulfillmentSetByIdRoutes.PostOutput,
  },
  {
    method: 'DELETE',
    matcher: '/admin/fulfillment-sets/:id',
    handler: fulfillmentSetByIdRoutes.DELETE,
    input: fulfillmentSetByIdRoutes.DeleteInput,
    operationId: 'deleteAdminFulfillmentSet',
    summary: 'Delete a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
    output: fulfillmentSetByIdRoutes.DeleteOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones',
    handler: serviceZoneRoutes.POST,
    input: serviceZoneRoutes.PostInput,
    operationId: 'createAdminServiceZone',
    summary: 'Create a service zone in a fulfillment set',
    tags: [Tags.FULFILLMENT_SETS],
    output: serviceZoneRoutes.PostOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    handler: serviceZoneByIdRoutes.GET,
    input: serviceZoneByIdRoutes.GetInput,
    operationId: 'getAdminServiceZone',
    summary: 'Retrieve a service zone with geo zones',
    tags: [Tags.FULFILLMENT_SETS],
    output: serviceZoneByIdRoutes.GetOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    handler: serviceZoneByIdRoutes.POST,
    input: serviceZoneByIdRoutes.PostInput,
    operationId: 'updateAdminServiceZone',
    summary: 'Update a service zone',
    tags: [Tags.FULFILLMENT_SETS],
    output: serviceZoneByIdRoutes.PostOutput,
  },
  {
    method: 'DELETE',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId',
    handler: serviceZoneByIdRoutes.DELETE,
    input: serviceZoneByIdRoutes.DeleteInput,
    operationId: 'deleteAdminServiceZone',
    summary: 'Delete a service zone',
    tags: [Tags.FULFILLMENT_SETS],
    output: serviceZoneByIdRoutes.DeleteOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/fulfillment-sets/:id/service-zones/:zoneId/geo-zones',
    handler: geoZoneRoutes.POST,
    input: geoZoneRoutes.PostInput,
    operationId: 'createAdminGeoZone',
    summary: 'Add a geo zone to a service zone',
    tags: [Tags.FULFILLMENT_SETS],
    output: geoZoneRoutes.PostOutput,
  },
] satisfies RouteDefinition[]
