// Generated by `npm run --workspace=@proteus/icons build:icons`. Do not edit.
import { createIcon } from '../src/create-icon.ts'
import type { IconNode } from '../src/types.ts'

const iconNode: IconNode = [
  [
    'path',
    {
      d: 'M4.592 2v20H0V2h4.592zm11.46 0c0 4.194-1.583 8.105-4.415 11.068l-.278.283L17.702 22h-5.668l-6.893-9.4 1.779-1.332c2.858-2.14 4.535-5.378 4.637-8.924L11.562 2h4.49zM21.5 17a2.5 2.5 0 110 5 2.5 2.5 0 010-5z',
      key: 'fv8g76',
    },
  ],
]

/**
 * @component @name KlarnaIcon
 * @description Klarna brand mark, rendered as an SVG element.
 *
 * @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+S2xhcm5hPC90aXRsZT48cGF0aCBkPSJNNC41OTIgMnYyMEgwVjJoNC41OTJ6bTExLjQ2IDBjMCA0LjE5NC0xLjU4MyA4LjEwNS00LjQxNSAxMS4wNjhsLS4yNzguMjgzTDE3LjcwMiAyMmgtNS42NjhsLTYuODkzLTkuNCAxLjc3OS0xLjMzMmMyLjg1OC0yLjE0IDQuNTM1LTUuMzc4IDQuNjM3LTguOTI0TDExLjU2MiAyaDQuNDl6TTIxLjUgMTdhMi41IDIuNSAwIDExMCA1IDIuNSAyLjUgMCAwMTAtNXoiLz48L3N2Zz4=)
 * @source assets/klarna.svg
 */
export const KlarnaIcon = createIcon('Klarna', iconNode)
