// Generated by `npm run --workspace=@proteus/icons build:icons`. Do not edit.
import { createIcon } from '../src/create-icon.ts'
import type { IconNode } from '../src/types.ts'

const iconNode: IconNode = [
  [
    'path',
    {
      d: 'M15.607 4.653H8.941L6.645 19.251H1.82L4.862 0h7.995c3.754 0 6.375 2.294 6.473 5.513-.648-.478-2.105-.86-3.722-.86m6.57 5.546c0 3.41-3.01 6.853-6.958 6.853h-2.493L11.595 24H6.74l1.845-11.538h3.592c4.208 0 7.346-3.634 7.153-6.949a5.24 5.24 0 0 1 2.848 4.686M9.653 5.546h6.408c.907 0 1.942.222 2.363.541-.195 2.741-2.655 5.483-6.441 5.483H8.714Z',
      key: '13syx1',
    },
  ],
]

/**
 * @component @name PaypalIcon
 * @description PayPal brand mark, rendered as an SVG element.
 *
 * @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+UGF5UGFsPC90aXRsZT48cGF0aCBkPSJNMTUuNjA3IDQuNjUzSDguOTQxTDYuNjQ1IDE5LjI1MUgxLjgyTDQuODYyIDBoNy45OTVjMy43NTQgMCA2LjM3NSAyLjI5NCA2LjQ3MyA1LjUxMy0uNjQ4LS40NzgtMi4xMDUtLjg2LTMuNzIyLS44Nm02LjU3IDUuNTQ2YzAgMy40MS0zLjAxIDYuODUzLTYuOTU4IDYuODUzaC0yLjQ5M0wxMS41OTUgMjRINi43NGwxLjg0NS0xMS41MzhoMy41OTJjNC4yMDggMCA3LjM0Ni0zLjYzNCA3LjE1My02Ljk0OWE1LjI0IDUuMjQgMCAwIDEgMi44NDggNC42ODZNOS42NTMgNS41NDZoNi40MDhjLjkwNyAwIDEuOTQyLjIyMiAyLjM2My41NDEtLjE5NSAyLjc0MS0yLjY1NSA1LjQ4My02LjQ0MSA1LjQ4M0g4LjcxNFoiLz48L3N2Zz4=)
 * @source assets/paypal.svg
 */
export const PaypalIcon = createIcon('Paypal', iconNode)
