// Generated by `npm run --workspace=@proteus/icons build:icons`. Do not edit.
import { createIcon } from '../src/create-icon.ts'
import type { IconAttributes, IconNode } from '../src/types.ts'

const iconAttributes: IconAttributes = {
  fill: 'none',
  viewBox: '0 0 24 24',
  strokeWidth: '1.5',
  stroke: 'currentColor',
}

const iconNode: IconNode = [
  [
    'path',
    {
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
      d: 'M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z',
      key: '1jzlfb',
    },
  ],
]

/**
 * @component @name ShoppingBagIcon
 * @description Shopping Bag, rendered as an SVG element.
 *
 * @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3Ryb2tlLXdpZHRoPSIxLjUiCiAgc3Ryb2tlPSJjdXJyZW50Q29sb3IiIGNsYXNzPSJzaXplLTYiPgogIDx0aXRsZT5TaG9wcGluZyBCYWc8L3RpdGxlPgogIDxwYXRoIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIKICAgIGQ9Ik0xNS43NSAxMC41VjZhMy43NSAzLjc1IDAgMSAwLTcuNSAwdjQuNW0xMS4zNTYtMS45OTMgMS4yNjMgMTJjLjA3LjY2NS0uNDUgMS4yNDMtMS4xMTkgMS4yNDNINC4yNWExLjEyNSAxLjEyNSAwIDAgMS0xLjEyLTEuMjQzbDEuMjY0LTEyQTEuMTI1IDEuMTI1IDAgMCAxIDUuNTEzIDcuNWgxMi45NzRjLjU3NiAwIDEuMDU5LjQzNSAxLjExOSAxLjAwN1pNOC42MjUgMTAuNWEuMzc1LjM3NSAwIDEgMS0uNzUgMCAuMzc1LjM3NSAwIDAgMSAuNzUgMFptNy41IDBhLjM3NS4zNzUgMCAxIDEtLjc1IDAgLjM3NS4zNzUgMCAwIDEgLjc1IDBaIiAvPgo8L3N2Zz4=)
 * @source assets/shopping-bag.svg
 */
export const ShoppingBagIcon = createIcon('ShoppingBag', iconNode, iconAttributes)
