/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthedShellRouteRouteImport } from './routes/_authed/_shell/route'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as PublicInviteRouteImport } from './routes/_public/invite'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedShellIndexRouteImport } from './routes/_authed/_shell/index'
import { Route as AuthedShellCustomersRouteImport } from './routes/_authed/_shell/customers'
import { Route as AuthedShellOrdersRouteRouteImport } from './routes/_authed/_shell/orders/route'
import { Route as AuthedShellProductOptionsRouteRouteImport } from './routes/_authed/_shell/product-options/route'
import { Route as AuthedShellProductsRouteRouteImport } from './routes/_authed/_shell/products/route'
import { Route as AuthedSettingsRegionsRouteRouteImport } from './routes/_authed/settings/regions/route'
import { Route as AuthedSettingsStoreRouteRouteImport } from './routes/_authed/settings/store/route'
import { Route as AuthedSettingsUsersRouteRouteImport } from './routes/_authed/settings/users/route'
import { Route as AuthedShellOrdersIndexRouteImport } from './routes/_authed/_shell/orders/index'
import { Route as AuthedShellOrdersIdRouteRouteImport } from './routes/_authed/_shell/orders/$id/route'
import { Route as AuthedShellProductOptionsIndexRouteImport } from './routes/_authed/_shell/product-options/index'
import { Route as AuthedShellProductOptionsIdRouteRouteImport } from './routes/_authed/_shell/product-options/$id/route'
import { Route as AuthedShellProductOptionsCreateRouteImport } from './routes/_authed/_shell/product-options/create'
import { Route as AuthedShellProductsIndexRouteImport } from './routes/_authed/_shell/products/index'
import { Route as AuthedShellProductsIdRouteRouteImport } from './routes/_authed/_shell/products/$id/route'
import { Route as AuthedShellProductsCreateRouteImport } from './routes/_authed/_shell/products/create'
import { Route as AuthedSettingsRegionsIndexRouteImport } from './routes/_authed/settings/regions/index'
import { Route as AuthedSettingsRegionsIdRouteRouteImport } from './routes/_authed/settings/regions/$id/route'
import { Route as AuthedSettingsRegionsCreateRouteImport } from './routes/_authed/settings/regions/create'
import { Route as AuthedSettingsStoreIndexRouteImport } from './routes/_authed/settings/store/index'
import { Route as AuthedSettingsStoreCurrenciesRouteImport } from './routes/_authed/settings/store/currencies'
import { Route as AuthedSettingsStoreEditRouteImport } from './routes/_authed/settings/store/edit'
import { Route as AuthedSettingsUsersInviteRouteImport } from './routes/_authed/settings/users/invite'
import { Route as AuthedShellOrdersIdDetailRouteRouteImport } from './routes/_authed/_shell/orders/$id/_detail/route'
import { Route as AuthedShellProductOptionsIdDetailRouteRouteImport } from './routes/_authed/_shell/product-options/$id/_detail/route'
import { Route as AuthedShellProductsIdDetailRouteRouteImport } from './routes/_authed/_shell/products/$id/_detail/route'
import { Route as AuthedSettingsRegionsIdDetailRouteRouteImport } from './routes/_authed/settings/regions/$id/_detail/route'
import { Route as AuthedShellOrdersIdDetailIndexRouteImport } from './routes/_authed/_shell/orders/$id/_detail/index'
import { Route as AuthedShellProductOptionsIdDetailIndexRouteImport } from './routes/_authed/_shell/product-options/$id/_detail/index'
import { Route as AuthedShellProductOptionsIdDetailEditRouteImport } from './routes/_authed/_shell/product-options/$id/_detail/edit'
import { Route as AuthedShellProductsIdDetailIndexRouteImport } from './routes/_authed/_shell/products/$id/_detail/index'
import { Route as AuthedShellProductsIdDetailEditRouteImport } from './routes/_authed/_shell/products/$id/_detail/edit'
import { Route as AuthedShellProductsIdDetailMediaRouteImport } from './routes/_authed/_shell/products/$id/_detail/media'
import { Route as AuthedShellProductsIdDetailOptionsRouteImport } from './routes/_authed/_shell/products/$id/_detail/options'
import { Route as AuthedShellProductsIdVariantsVariantIdRouteRouteImport } from './routes/_authed/_shell/products/$id/variants/$variantId/route'
import { Route as AuthedShellProductsIdVariantsCreateRouteImport } from './routes/_authed/_shell/products/$id/variants/create'
import { Route as AuthedSettingsRegionsIdDetailIndexRouteImport } from './routes/_authed/settings/regions/$id/_detail/index'
import { Route as AuthedSettingsRegionsIdDetailEditRouteImport } from './routes/_authed/settings/regions/$id/_detail/edit'
import { Route as AuthedShellProductsIdVariantsVariantIdEditRouteImport } from './routes/_authed/_shell/products/$id/variants/$variantId/edit'
import { Route as AuthedShellProductsIdVariantsVariantIdMediaRouteImport } from './routes/_authed/_shell/products/$id/variants/$variantId/media'
import { Route as AuthedShellProductsIdVariantsVariantIdPricesRouteRouteImport } from './routes/_authed/_shell/products/$id/variants/$variantId/prices/route'
import { Route as AuthedSettingsRegionsIdDetailCountriesIndexRouteImport } from './routes/_authed/settings/regions/$id/_detail/countries/index'
import { Route as AuthedSettingsRegionsIdDetailCountriesCodeRouteImport } from './routes/_authed/settings/regions/$id/_detail/countries/$code'
import { Route as AuthedShellProductsIdDetailImagesImageIdVariantsRouteImport } from './routes/_authed/_shell/products/$id/_detail/images/$imageId/variants'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedShellRouteRoute = AuthedShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const PublicInviteRoute = PublicInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthedShellIndexRoute = AuthedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedShellRouteRoute,
} as any)
const AuthedShellCustomersRoute = AuthedShellCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedShellRouteRoute,
} as any)
const AuthedShellOrdersRouteRoute = AuthedShellOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedShellRouteRoute,
} as any)
const AuthedShellProductOptionsRouteRoute =
  AuthedShellProductOptionsRouteRouteImport.update({
    id: '/product-options',
    path: '/product-options',
    getParentRoute: () => AuthedShellRouteRoute,
  } as any)
const AuthedShellProductsRouteRoute =
  AuthedShellProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthedShellRouteRoute,
  } as any)
const AuthedSettingsRegionsRouteRoute =
  AuthedSettingsRegionsRouteRouteImport.update({
    id: '/regions',
    path: '/regions',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsStoreRouteRoute =
  AuthedSettingsStoreRouteRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsUsersRouteRoute =
  AuthedSettingsUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedShellOrdersIndexRoute = AuthedShellOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedShellOrdersRouteRoute,
} as any)
const AuthedShellOrdersIdRouteRoute =
  AuthedShellOrdersIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedShellOrdersRouteRoute,
  } as any)
const AuthedShellProductOptionsIndexRoute =
  AuthedShellProductOptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedShellProductOptionsRouteRoute,
  } as any)
const AuthedShellProductOptionsIdRouteRoute =
  AuthedShellProductOptionsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedShellProductOptionsRouteRoute,
  } as any)
const AuthedShellProductOptionsCreateRoute =
  AuthedShellProductOptionsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthedShellProductOptionsRouteRoute,
  } as any)
const AuthedShellProductsIndexRoute =
  AuthedShellProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedShellProductsRouteRoute,
  } as any)
const AuthedShellProductsIdRouteRoute =
  AuthedShellProductsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedShellProductsRouteRoute,
  } as any)
const AuthedShellProductsCreateRoute =
  AuthedShellProductsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthedShellProductsRouteRoute,
  } as any)
const AuthedSettingsRegionsIndexRoute =
  AuthedSettingsRegionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSettingsRegionsRouteRoute,
  } as any)
const AuthedSettingsRegionsIdRouteRoute =
  AuthedSettingsRegionsIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedSettingsRegionsRouteRoute,
  } as any)
const AuthedSettingsRegionsCreateRoute =
  AuthedSettingsRegionsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthedSettingsRegionsRouteRoute,
  } as any)
const AuthedSettingsStoreIndexRoute =
  AuthedSettingsStoreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSettingsStoreRouteRoute,
  } as any)
const AuthedSettingsStoreCurrenciesRoute =
  AuthedSettingsStoreCurrenciesRouteImport.update({
    id: '/currencies',
    path: '/currencies',
    getParentRoute: () => AuthedSettingsStoreRouteRoute,
  } as any)
const AuthedSettingsStoreEditRoute = AuthedSettingsStoreEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthedSettingsStoreRouteRoute,
} as any)
const AuthedSettingsUsersInviteRoute =
  AuthedSettingsUsersInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AuthedSettingsUsersRouteRoute,
  } as any)
const AuthedShellOrdersIdDetailRouteRoute =
  AuthedShellOrdersIdDetailRouteRouteImport.update({
    id: '/_detail',
    getParentRoute: () => AuthedShellOrdersIdRouteRoute,
  } as any)
const AuthedShellProductOptionsIdDetailRouteRoute =
  AuthedShellProductOptionsIdDetailRouteRouteImport.update({
    id: '/_detail',
    getParentRoute: () => AuthedShellProductOptionsIdRouteRoute,
  } as any)
const AuthedShellProductsIdDetailRouteRoute =
  AuthedShellProductsIdDetailRouteRouteImport.update({
    id: '/_detail',
    getParentRoute: () => AuthedShellProductsIdRouteRoute,
  } as any)
const AuthedSettingsRegionsIdDetailRouteRoute =
  AuthedSettingsRegionsIdDetailRouteRouteImport.update({
    id: '/_detail',
    getParentRoute: () => AuthedSettingsRegionsIdRouteRoute,
  } as any)
const AuthedShellOrdersIdDetailIndexRoute =
  AuthedShellOrdersIdDetailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedShellOrdersIdDetailRouteRoute,
  } as any)
const AuthedShellProductOptionsIdDetailIndexRoute =
  AuthedShellProductOptionsIdDetailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedShellProductOptionsIdDetailRouteRoute,
  } as any)
const AuthedShellProductOptionsIdDetailEditRoute =
  AuthedShellProductOptionsIdDetailEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedShellProductOptionsIdDetailRouteRoute,
  } as any)
const AuthedShellProductsIdDetailIndexRoute =
  AuthedShellProductsIdDetailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedShellProductsIdDetailRouteRoute,
  } as any)
const AuthedShellProductsIdDetailEditRoute =
  AuthedShellProductsIdDetailEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedShellProductsIdDetailRouteRoute,
  } as any)
const AuthedShellProductsIdDetailMediaRoute =
  AuthedShellProductsIdDetailMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthedShellProductsIdDetailRouteRoute,
  } as any)
const AuthedShellProductsIdDetailOptionsRoute =
  AuthedShellProductsIdDetailOptionsRouteImport.update({
    id: '/options',
    path: '/options',
    getParentRoute: () => AuthedShellProductsIdDetailRouteRoute,
  } as any)
const AuthedShellProductsIdVariantsVariantIdRouteRoute =
  AuthedShellProductsIdVariantsVariantIdRouteRouteImport.update({
    id: '/variants/$variantId',
    path: '/variants/$variantId',
    getParentRoute: () => AuthedShellProductsIdRouteRoute,
  } as any)
const AuthedShellProductsIdVariantsCreateRoute =
  AuthedShellProductsIdVariantsCreateRouteImport.update({
    id: '/variants/create',
    path: '/variants/create',
    getParentRoute: () => AuthedShellProductsIdRouteRoute,
  } as any)
const AuthedSettingsRegionsIdDetailIndexRoute =
  AuthedSettingsRegionsIdDetailIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedSettingsRegionsIdDetailRouteRoute,
  } as any)
const AuthedSettingsRegionsIdDetailEditRoute =
  AuthedSettingsRegionsIdDetailEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedSettingsRegionsIdDetailRouteRoute,
  } as any)
const AuthedShellProductsIdVariantsVariantIdEditRoute =
  AuthedShellProductsIdVariantsVariantIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthedShellProductsIdVariantsVariantIdRouteRoute,
  } as any)
const AuthedShellProductsIdVariantsVariantIdMediaRoute =
  AuthedShellProductsIdVariantsVariantIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthedShellProductsIdVariantsVariantIdRouteRoute,
  } as any)
const AuthedShellProductsIdVariantsVariantIdPricesRouteRoute =
  AuthedShellProductsIdVariantsVariantIdPricesRouteRouteImport.update({
    id: '/prices',
    path: '/prices',
    getParentRoute: () => AuthedShellProductsIdVariantsVariantIdRouteRoute,
  } as any)
const AuthedSettingsRegionsIdDetailCountriesIndexRoute =
  AuthedSettingsRegionsIdDetailCountriesIndexRouteImport.update({
    id: '/countries/',
    path: '/countries/',
    getParentRoute: () => AuthedSettingsRegionsIdDetailRouteRoute,
  } as any)
const AuthedSettingsRegionsIdDetailCountriesCodeRoute =
  AuthedSettingsRegionsIdDetailCountriesCodeRouteImport.update({
    id: '/countries/$code',
    path: '/countries/$code',
    getParentRoute: () => AuthedSettingsRegionsIdDetailRouteRoute,
  } as any)
const AuthedShellProductsIdDetailImagesImageIdVariantsRoute =
  AuthedShellProductsIdDetailImagesImageIdVariantsRouteImport.update({
    id: '/images/$imageId/variants',
    path: '/images/$imageId/variants',
    getParentRoute: () => AuthedShellProductsIdDetailRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedShellIndexRoute
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/invite': typeof PublicInviteRoute
  '/login': typeof PublicLoginRoute
  '/orders': typeof AuthedShellOrdersRouteRouteWithChildren
  '/product-options': typeof AuthedShellProductOptionsRouteRouteWithChildren
  '/products': typeof AuthedShellProductsRouteRouteWithChildren
  '/settings/regions': typeof AuthedSettingsRegionsRouteRouteWithChildren
  '/settings/store': typeof AuthedSettingsStoreRouteRouteWithChildren
  '/settings/users': typeof AuthedSettingsUsersRouteRouteWithChildren
  '/customers': typeof AuthedShellCustomersRoute
  '/orders/$id': typeof AuthedShellOrdersIdRouteRouteWithChildren
  '/product-options/$id': typeof AuthedShellProductOptionsIdRouteRouteWithChildren
  '/products/$id': typeof AuthedShellProductsIdRouteRouteWithChildren
  '/settings/regions/$id': typeof AuthedSettingsRegionsIdRouteRouteWithChildren
  '/product-options/create': typeof AuthedShellProductOptionsCreateRoute
  '/products/create': typeof AuthedShellProductsCreateRoute
  '/settings/regions/create': typeof AuthedSettingsRegionsCreateRoute
  '/settings/store/currencies': typeof AuthedSettingsStoreCurrenciesRoute
  '/settings/store/edit': typeof AuthedSettingsStoreEditRoute
  '/settings/users/invite': typeof AuthedSettingsUsersInviteRoute
  '/orders/': typeof AuthedShellOrdersIndexRoute
  '/product-options/': typeof AuthedShellProductOptionsIndexRoute
  '/products/': typeof AuthedShellProductsIndexRoute
  '/settings/regions/': typeof AuthedSettingsRegionsIndexRoute
  '/settings/store/': typeof AuthedSettingsStoreIndexRoute
  '/products/$id/variants/$variantId': typeof AuthedShellProductsIdVariantsVariantIdRouteRouteWithChildren
  '/product-options/$id/edit': typeof AuthedShellProductOptionsIdDetailEditRoute
  '/products/$id/edit': typeof AuthedShellProductsIdDetailEditRoute
  '/products/$id/media': typeof AuthedShellProductsIdDetailMediaRoute
  '/products/$id/options': typeof AuthedShellProductsIdDetailOptionsRoute
  '/products/$id/variants/create': typeof AuthedShellProductsIdVariantsCreateRoute
  '/settings/regions/$id/edit': typeof AuthedSettingsRegionsIdDetailEditRoute
  '/orders/$id/': typeof AuthedShellOrdersIdDetailIndexRoute
  '/product-options/$id/': typeof AuthedShellProductOptionsIdDetailIndexRoute
  '/products/$id/': typeof AuthedShellProductsIdDetailIndexRoute
  '/settings/regions/$id/': typeof AuthedSettingsRegionsIdDetailIndexRoute
  '/products/$id/variants/$variantId/prices': typeof AuthedShellProductsIdVariantsVariantIdPricesRouteRoute
  '/products/$id/variants/$variantId/edit': typeof AuthedShellProductsIdVariantsVariantIdEditRoute
  '/products/$id/variants/$variantId/media': typeof AuthedShellProductsIdVariantsVariantIdMediaRoute
  '/settings/regions/$id/countries/$code': typeof AuthedSettingsRegionsIdDetailCountriesCodeRoute
  '/settings/regions/$id/countries/': typeof AuthedSettingsRegionsIdDetailCountriesIndexRoute
  '/products/$id/images/$imageId/variants': typeof AuthedShellProductsIdDetailImagesImageIdVariantsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedShellIndexRoute
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/invite': typeof PublicInviteRoute
  '/login': typeof PublicLoginRoute
  '/settings/users': typeof AuthedSettingsUsersRouteRouteWithChildren
  '/customers': typeof AuthedShellCustomersRoute
  '/orders/$id': typeof AuthedShellOrdersIdDetailIndexRoute
  '/product-options/$id': typeof AuthedShellProductOptionsIdDetailIndexRoute
  '/products/$id': typeof AuthedShellProductsIdDetailIndexRoute
  '/settings/regions/$id': typeof AuthedSettingsRegionsIdDetailIndexRoute
  '/product-options/create': typeof AuthedShellProductOptionsCreateRoute
  '/products/create': typeof AuthedShellProductsCreateRoute
  '/settings/regions/create': typeof AuthedSettingsRegionsCreateRoute
  '/settings/store/currencies': typeof AuthedSettingsStoreCurrenciesRoute
  '/settings/store/edit': typeof AuthedSettingsStoreEditRoute
  '/settings/users/invite': typeof AuthedSettingsUsersInviteRoute
  '/orders': typeof AuthedShellOrdersIndexRoute
  '/product-options': typeof AuthedShellProductOptionsIndexRoute
  '/products': typeof AuthedShellProductsIndexRoute
  '/settings/regions': typeof AuthedSettingsRegionsIndexRoute
  '/settings/store': typeof AuthedSettingsStoreIndexRoute
  '/products/$id/variants/$variantId': typeof AuthedShellProductsIdVariantsVariantIdRouteRouteWithChildren
  '/product-options/$id/edit': typeof AuthedShellProductOptionsIdDetailEditRoute
  '/products/$id/edit': typeof AuthedShellProductsIdDetailEditRoute
  '/products/$id/media': typeof AuthedShellProductsIdDetailMediaRoute
  '/products/$id/options': typeof AuthedShellProductsIdDetailOptionsRoute
  '/products/$id/variants/create': typeof AuthedShellProductsIdVariantsCreateRoute
  '/settings/regions/$id/edit': typeof AuthedSettingsRegionsIdDetailEditRoute
  '/products/$id/variants/$variantId/prices': typeof AuthedShellProductsIdVariantsVariantIdPricesRouteRoute
  '/products/$id/variants/$variantId/edit': typeof AuthedShellProductsIdVariantsVariantIdEditRoute
  '/products/$id/variants/$variantId/media': typeof AuthedShellProductsIdVariantsVariantIdMediaRoute
  '/settings/regions/$id/countries/$code': typeof AuthedSettingsRegionsIdDetailCountriesCodeRoute
  '/settings/regions/$id/countries': typeof AuthedSettingsRegionsIdDetailCountriesIndexRoute
  '/products/$id/images/$imageId/variants': typeof AuthedShellProductsIdDetailImagesImageIdVariantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authed/_shell': typeof AuthedShellRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_public/invite': typeof PublicInviteRoute
  '/_public/login': typeof PublicLoginRoute
  '/_authed/_shell/orders': typeof AuthedShellOrdersRouteRouteWithChildren
  '/_authed/_shell/product-options': typeof AuthedShellProductOptionsRouteRouteWithChildren
  '/_authed/_shell/products': typeof AuthedShellProductsRouteRouteWithChildren
  '/_authed/settings/regions': typeof AuthedSettingsRegionsRouteRouteWithChildren
  '/_authed/settings/store': typeof AuthedSettingsStoreRouteRouteWithChildren
  '/_authed/settings/users': typeof AuthedSettingsUsersRouteRouteWithChildren
  '/_authed/_shell/customers': typeof AuthedShellCustomersRoute
  '/_authed/_shell/': typeof AuthedShellIndexRoute
  '/_authed/_shell/orders/$id': typeof AuthedShellOrdersIdRouteRouteWithChildren
  '/_authed/_shell/product-options/$id': typeof AuthedShellProductOptionsIdRouteRouteWithChildren
  '/_authed/_shell/products/$id': typeof AuthedShellProductsIdRouteRouteWithChildren
  '/_authed/settings/regions/$id': typeof AuthedSettingsRegionsIdRouteRouteWithChildren
  '/_authed/_shell/product-options/create': typeof AuthedShellProductOptionsCreateRoute
  '/_authed/_shell/products/create': typeof AuthedShellProductsCreateRoute
  '/_authed/settings/regions/create': typeof AuthedSettingsRegionsCreateRoute
  '/_authed/settings/store/currencies': typeof AuthedSettingsStoreCurrenciesRoute
  '/_authed/settings/store/edit': typeof AuthedSettingsStoreEditRoute
  '/_authed/settings/users/invite': typeof AuthedSettingsUsersInviteRoute
  '/_authed/_shell/orders/': typeof AuthedShellOrdersIndexRoute
  '/_authed/_shell/product-options/': typeof AuthedShellProductOptionsIndexRoute
  '/_authed/_shell/products/': typeof AuthedShellProductsIndexRoute
  '/_authed/settings/regions/': typeof AuthedSettingsRegionsIndexRoute
  '/_authed/settings/store/': typeof AuthedSettingsStoreIndexRoute
  '/_authed/_shell/orders/$id/_detail': typeof AuthedShellOrdersIdDetailRouteRouteWithChildren
  '/_authed/_shell/product-options/$id/_detail': typeof AuthedShellProductOptionsIdDetailRouteRouteWithChildren
  '/_authed/_shell/products/$id/_detail': typeof AuthedShellProductsIdDetailRouteRouteWithChildren
  '/_authed/settings/regions/$id/_detail': typeof AuthedSettingsRegionsIdDetailRouteRouteWithChildren
  '/_authed/_shell/products/$id/variants/$variantId': typeof AuthedShellProductsIdVariantsVariantIdRouteRouteWithChildren
  '/_authed/_shell/product-options/$id/_detail/edit': typeof AuthedShellProductOptionsIdDetailEditRoute
  '/_authed/_shell/products/$id/_detail/edit': typeof AuthedShellProductsIdDetailEditRoute
  '/_authed/_shell/products/$id/_detail/media': typeof AuthedShellProductsIdDetailMediaRoute
  '/_authed/_shell/products/$id/_detail/options': typeof AuthedShellProductsIdDetailOptionsRoute
  '/_authed/_shell/products/$id/variants/create': typeof AuthedShellProductsIdVariantsCreateRoute
  '/_authed/settings/regions/$id/_detail/edit': typeof AuthedSettingsRegionsIdDetailEditRoute
  '/_authed/_shell/orders/$id/_detail/': typeof AuthedShellOrdersIdDetailIndexRoute
  '/_authed/_shell/product-options/$id/_detail/': typeof AuthedShellProductOptionsIdDetailIndexRoute
  '/_authed/_shell/products/$id/_detail/': typeof AuthedShellProductsIdDetailIndexRoute
  '/_authed/settings/regions/$id/_detail/': typeof AuthedSettingsRegionsIdDetailIndexRoute
  '/_authed/_shell/products/$id/variants/$variantId/prices': typeof AuthedShellProductsIdVariantsVariantIdPricesRouteRoute
  '/_authed/_shell/products/$id/variants/$variantId/edit': typeof AuthedShellProductsIdVariantsVariantIdEditRoute
  '/_authed/_shell/products/$id/variants/$variantId/media': typeof AuthedShellProductsIdVariantsVariantIdMediaRoute
  '/_authed/settings/regions/$id/_detail/countries/$code': typeof AuthedSettingsRegionsIdDetailCountriesCodeRoute
  '/_authed/settings/regions/$id/_detail/countries/': typeof AuthedSettingsRegionsIdDetailCountriesIndexRoute
  '/_authed/_shell/products/$id/_detail/images/$imageId/variants': typeof AuthedShellProductsIdDetailImagesImageIdVariantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/invite'
    | '/login'
    | '/orders'
    | '/product-options'
    | '/products'
    | '/settings/regions'
    | '/settings/store'
    | '/settings/users'
    | '/customers'
    | '/orders/$id'
    | '/product-options/$id'
    | '/products/$id'
    | '/settings/regions/$id'
    | '/product-options/create'
    | '/products/create'
    | '/settings/regions/create'
    | '/settings/store/currencies'
    | '/settings/store/edit'
    | '/settings/users/invite'
    | '/orders/'
    | '/product-options/'
    | '/products/'
    | '/settings/regions/'
    | '/settings/store/'
    | '/products/$id/variants/$variantId'
    | '/product-options/$id/edit'
    | '/products/$id/edit'
    | '/products/$id/media'
    | '/products/$id/options'
    | '/products/$id/variants/create'
    | '/settings/regions/$id/edit'
    | '/orders/$id/'
    | '/product-options/$id/'
    | '/products/$id/'
    | '/settings/regions/$id/'
    | '/products/$id/variants/$variantId/prices'
    | '/products/$id/variants/$variantId/edit'
    | '/products/$id/variants/$variantId/media'
    | '/settings/regions/$id/countries/$code'
    | '/settings/regions/$id/countries/'
    | '/products/$id/images/$imageId/variants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/invite'
    | '/login'
    | '/settings/users'
    | '/customers'
    | '/orders/$id'
    | '/product-options/$id'
    | '/products/$id'
    | '/settings/regions/$id'
    | '/product-options/create'
    | '/products/create'
    | '/settings/regions/create'
    | '/settings/store/currencies'
    | '/settings/store/edit'
    | '/settings/users/invite'
    | '/orders'
    | '/product-options'
    | '/products'
    | '/settings/regions'
    | '/settings/store'
    | '/products/$id/variants/$variantId'
    | '/product-options/$id/edit'
    | '/products/$id/edit'
    | '/products/$id/media'
    | '/products/$id/options'
    | '/products/$id/variants/create'
    | '/settings/regions/$id/edit'
    | '/products/$id/variants/$variantId/prices'
    | '/products/$id/variants/$variantId/edit'
    | '/products/$id/variants/$variantId/media'
    | '/settings/regions/$id/countries/$code'
    | '/settings/regions/$id/countries'
    | '/products/$id/images/$imageId/variants'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/_shell'
    | '/_authed/settings'
    | '/_public/invite'
    | '/_public/login'
    | '/_authed/_shell/orders'
    | '/_authed/_shell/product-options'
    | '/_authed/_shell/products'
    | '/_authed/settings/regions'
    | '/_authed/settings/store'
    | '/_authed/settings/users'
    | '/_authed/_shell/customers'
    | '/_authed/_shell/'
    | '/_authed/_shell/orders/$id'
    | '/_authed/_shell/product-options/$id'
    | '/_authed/_shell/products/$id'
    | '/_authed/settings/regions/$id'
    | '/_authed/_shell/product-options/create'
    | '/_authed/_shell/products/create'
    | '/_authed/settings/regions/create'
    | '/_authed/settings/store/currencies'
    | '/_authed/settings/store/edit'
    | '/_authed/settings/users/invite'
    | '/_authed/_shell/orders/'
    | '/_authed/_shell/product-options/'
    | '/_authed/_shell/products/'
    | '/_authed/settings/regions/'
    | '/_authed/settings/store/'
    | '/_authed/_shell/orders/$id/_detail'
    | '/_authed/_shell/product-options/$id/_detail'
    | '/_authed/_shell/products/$id/_detail'
    | '/_authed/settings/regions/$id/_detail'
    | '/_authed/_shell/products/$id/variants/$variantId'
    | '/_authed/_shell/product-options/$id/_detail/edit'
    | '/_authed/_shell/products/$id/_detail/edit'
    | '/_authed/_shell/products/$id/_detail/media'
    | '/_authed/_shell/products/$id/_detail/options'
    | '/_authed/_shell/products/$id/variants/create'
    | '/_authed/settings/regions/$id/_detail/edit'
    | '/_authed/_shell/orders/$id/_detail/'
    | '/_authed/_shell/product-options/$id/_detail/'
    | '/_authed/_shell/products/$id/_detail/'
    | '/_authed/settings/regions/$id/_detail/'
    | '/_authed/_shell/products/$id/variants/$variantId/prices'
    | '/_authed/_shell/products/$id/variants/$variantId/edit'
    | '/_authed/_shell/products/$id/variants/$variantId/media'
    | '/_authed/settings/regions/$id/_detail/countries/$code'
    | '/_authed/settings/regions/$id/_detail/countries/'
    | '/_authed/_shell/products/$id/_detail/images/$imageId/variants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_shell': {
      id: '/_authed/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedShellRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_public/invite': {
      id: '/_public/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof PublicInviteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authed/_shell/': {
      id: '/_authed/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedShellIndexRouteImport
      parentRoute: typeof AuthedShellRouteRoute
    }
    '/_authed/_shell/customers': {
      id: '/_authed/_shell/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedShellCustomersRouteImport
      parentRoute: typeof AuthedShellRouteRoute
    }
    '/_authed/_shell/orders': {
      id: '/_authed/_shell/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedShellOrdersRouteRouteImport
      parentRoute: typeof AuthedShellRouteRoute
    }
    '/_authed/_shell/product-options': {
      id: '/_authed/_shell/product-options'
      path: '/product-options'
      fullPath: '/product-options'
      preLoaderRoute: typeof AuthedShellProductOptionsRouteRouteImport
      parentRoute: typeof AuthedShellRouteRoute
    }
    '/_authed/_shell/products': {
      id: '/_authed/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedShellProductsRouteRouteImport
      parentRoute: typeof AuthedShellRouteRoute
    }
    '/_authed/settings/regions': {
      id: '/_authed/settings/regions'
      path: '/regions'
      fullPath: '/settings/regions'
      preLoaderRoute: typeof AuthedSettingsRegionsRouteRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/store': {
      id: '/_authed/settings/store'
      path: '/store'
      fullPath: '/settings/store'
      preLoaderRoute: typeof AuthedSettingsStoreRouteRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/users': {
      id: '/_authed/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthedSettingsUsersRouteRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/_shell/orders/': {
      id: '/_authed/_shell/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedShellOrdersIndexRouteImport
      parentRoute: typeof AuthedShellOrdersRouteRoute
    }
    '/_authed/_shell/orders/$id': {
      id: '/_authed/_shell/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthedShellOrdersIdRouteRouteImport
      parentRoute: typeof AuthedShellOrdersRouteRoute
    }
    '/_authed/_shell/product-options/': {
      id: '/_authed/_shell/product-options/'
      path: '/'
      fullPath: '/product-options/'
      preLoaderRoute: typeof AuthedShellProductOptionsIndexRouteImport
      parentRoute: typeof AuthedShellProductOptionsRouteRoute
    }
    '/_authed/_shell/product-options/$id': {
      id: '/_authed/_shell/product-options/$id'
      path: '/$id'
      fullPath: '/product-options/$id'
      preLoaderRoute: typeof AuthedShellProductOptionsIdRouteRouteImport
      parentRoute: typeof AuthedShellProductOptionsRouteRoute
    }
    '/_authed/_shell/product-options/create': {
      id: '/_authed/_shell/product-options/create'
      path: '/create'
      fullPath: '/product-options/create'
      preLoaderRoute: typeof AuthedShellProductOptionsCreateRouteImport
      parentRoute: typeof AuthedShellProductOptionsRouteRoute
    }
    '/_authed/_shell/products/': {
      id: '/_authed/_shell/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedShellProductsIndexRouteImport
      parentRoute: typeof AuthedShellProductsRouteRoute
    }
    '/_authed/_shell/products/$id': {
      id: '/_authed/_shell/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedShellProductsIdRouteRouteImport
      parentRoute: typeof AuthedShellProductsRouteRoute
    }
    '/_authed/_shell/products/create': {
      id: '/_authed/_shell/products/create'
      path: '/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof AuthedShellProductsCreateRouteImport
      parentRoute: typeof AuthedShellProductsRouteRoute
    }
    '/_authed/settings/regions/': {
      id: '/_authed/settings/regions/'
      path: '/'
      fullPath: '/settings/regions/'
      preLoaderRoute: typeof AuthedSettingsRegionsIndexRouteImport
      parentRoute: typeof AuthedSettingsRegionsRouteRoute
    }
    '/_authed/settings/regions/$id': {
      id: '/_authed/settings/regions/$id'
      path: '/$id'
      fullPath: '/settings/regions/$id'
      preLoaderRoute: typeof AuthedSettingsRegionsIdRouteRouteImport
      parentRoute: typeof AuthedSettingsRegionsRouteRoute
    }
    '/_authed/settings/regions/create': {
      id: '/_authed/settings/regions/create'
      path: '/create'
      fullPath: '/settings/regions/create'
      preLoaderRoute: typeof AuthedSettingsRegionsCreateRouteImport
      parentRoute: typeof AuthedSettingsRegionsRouteRoute
    }
    '/_authed/settings/store/': {
      id: '/_authed/settings/store/'
      path: '/'
      fullPath: '/settings/store/'
      preLoaderRoute: typeof AuthedSettingsStoreIndexRouteImport
      parentRoute: typeof AuthedSettingsStoreRouteRoute
    }
    '/_authed/settings/store/currencies': {
      id: '/_authed/settings/store/currencies'
      path: '/currencies'
      fullPath: '/settings/store/currencies'
      preLoaderRoute: typeof AuthedSettingsStoreCurrenciesRouteImport
      parentRoute: typeof AuthedSettingsStoreRouteRoute
    }
    '/_authed/settings/store/edit': {
      id: '/_authed/settings/store/edit'
      path: '/edit'
      fullPath: '/settings/store/edit'
      preLoaderRoute: typeof AuthedSettingsStoreEditRouteImport
      parentRoute: typeof AuthedSettingsStoreRouteRoute
    }
    '/_authed/settings/users/invite': {
      id: '/_authed/settings/users/invite'
      path: '/invite'
      fullPath: '/settings/users/invite'
      preLoaderRoute: typeof AuthedSettingsUsersInviteRouteImport
      parentRoute: typeof AuthedSettingsUsersRouteRoute
    }
    '/_authed/_shell/orders/$id/_detail': {
      id: '/_authed/_shell/orders/$id/_detail'
      path: ''
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthedShellOrdersIdDetailRouteRouteImport
      parentRoute: typeof AuthedShellOrdersIdRouteRoute
    }
    '/_authed/_shell/product-options/$id/_detail': {
      id: '/_authed/_shell/product-options/$id/_detail'
      path: ''
      fullPath: '/product-options/$id'
      preLoaderRoute: typeof AuthedShellProductOptionsIdDetailRouteRouteImport
      parentRoute: typeof AuthedShellProductOptionsIdRouteRoute
    }
    '/_authed/_shell/products/$id/_detail': {
      id: '/_authed/_shell/products/$id/_detail'
      path: ''
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthedShellProductsIdDetailRouteRouteImport
      parentRoute: typeof AuthedShellProductsIdRouteRoute
    }
    '/_authed/settings/regions/$id/_detail': {
      id: '/_authed/settings/regions/$id/_detail'
      path: ''
      fullPath: '/settings/regions/$id'
      preLoaderRoute: typeof AuthedSettingsRegionsIdDetailRouteRouteImport
      parentRoute: typeof AuthedSettingsRegionsIdRouteRoute
    }
    '/_authed/_shell/orders/$id/_detail/': {
      id: '/_authed/_shell/orders/$id/_detail/'
      path: '/'
      fullPath: '/orders/$id/'
      preLoaderRoute: typeof AuthedShellOrdersIdDetailIndexRouteImport
      parentRoute: typeof AuthedShellOrdersIdDetailRouteRoute
    }
    '/_authed/_shell/product-options/$id/_detail/': {
      id: '/_authed/_shell/product-options/$id/_detail/'
      path: '/'
      fullPath: '/product-options/$id/'
      preLoaderRoute: typeof AuthedShellProductOptionsIdDetailIndexRouteImport
      parentRoute: typeof AuthedShellProductOptionsIdDetailRouteRoute
    }
    '/_authed/_shell/product-options/$id/_detail/edit': {
      id: '/_authed/_shell/product-options/$id/_detail/edit'
      path: '/edit'
      fullPath: '/product-options/$id/edit'
      preLoaderRoute: typeof AuthedShellProductOptionsIdDetailEditRouteImport
      parentRoute: typeof AuthedShellProductOptionsIdDetailRouteRoute
    }
    '/_authed/_shell/products/$id/_detail/': {
      id: '/_authed/_shell/products/$id/_detail/'
      path: '/'
      fullPath: '/products/$id/'
      preLoaderRoute: typeof AuthedShellProductsIdDetailIndexRouteImport
      parentRoute: typeof AuthedShellProductsIdDetailRouteRoute
    }
    '/_authed/_shell/products/$id/_detail/edit': {
      id: '/_authed/_shell/products/$id/_detail/edit'
      path: '/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AuthedShellProductsIdDetailEditRouteImport
      parentRoute: typeof AuthedShellProductsIdDetailRouteRoute
    }
    '/_authed/_shell/products/$id/_detail/media': {
      id: '/_authed/_shell/products/$id/_detail/media'
      path: '/media'
      fullPath: '/products/$id/media'
      preLoaderRoute: typeof AuthedShellProductsIdDetailMediaRouteImport
      parentRoute: typeof AuthedShellProductsIdDetailRouteRoute
    }
    '/_authed/_shell/products/$id/_detail/options': {
      id: '/_authed/_shell/products/$id/_detail/options'
      path: '/options'
      fullPath: '/products/$id/options'
      preLoaderRoute: typeof AuthedShellProductsIdDetailOptionsRouteImport
      parentRoute: typeof AuthedShellProductsIdDetailRouteRoute
    }
    '/_authed/_shell/products/$id/variants/$variantId': {
      id: '/_authed/_shell/products/$id/variants/$variantId'
      path: '/variants/$variantId'
      fullPath: '/products/$id/variants/$variantId'
      preLoaderRoute: typeof AuthedShellProductsIdVariantsVariantIdRouteRouteImport
      parentRoute: typeof AuthedShellProductsIdRouteRoute
    }
    '/_authed/_shell/products/$id/variants/create': {
      id: '/_authed/_shell/products/$id/variants/create'
      path: '/variants/create'
      fullPath: '/products/$id/variants/create'
      preLoaderRoute: typeof AuthedShellProductsIdVariantsCreateRouteImport
      parentRoute: typeof AuthedShellProductsIdRouteRoute
    }
    '/_authed/settings/regions/$id/_detail/': {
      id: '/_authed/settings/regions/$id/_detail/'
      path: '/'
      fullPath: '/settings/regions/$id/'
      preLoaderRoute: typeof AuthedSettingsRegionsIdDetailIndexRouteImport
      parentRoute: typeof AuthedSettingsRegionsIdDetailRouteRoute
    }
    '/_authed/settings/regions/$id/_detail/edit': {
      id: '/_authed/settings/regions/$id/_detail/edit'
      path: '/edit'
      fullPath: '/settings/regions/$id/edit'
      preLoaderRoute: typeof AuthedSettingsRegionsIdDetailEditRouteImport
      parentRoute: typeof AuthedSettingsRegionsIdDetailRouteRoute
    }
    '/_authed/_shell/products/$id/variants/$variantId/edit': {
      id: '/_authed/_shell/products/$id/variants/$variantId/edit'
      path: '/edit'
      fullPath: '/products/$id/variants/$variantId/edit'
      preLoaderRoute: typeof AuthedShellProductsIdVariantsVariantIdEditRouteImport
      parentRoute: typeof AuthedShellProductsIdVariantsVariantIdRouteRoute
    }
    '/_authed/_shell/products/$id/variants/$variantId/media': {
      id: '/_authed/_shell/products/$id/variants/$variantId/media'
      path: '/media'
      fullPath: '/products/$id/variants/$variantId/media'
      preLoaderRoute: typeof AuthedShellProductsIdVariantsVariantIdMediaRouteImport
      parentRoute: typeof AuthedShellProductsIdVariantsVariantIdRouteRoute
    }
    '/_authed/_shell/products/$id/variants/$variantId/prices': {
      id: '/_authed/_shell/products/$id/variants/$variantId/prices'
      path: '/prices'
      fullPath: '/products/$id/variants/$variantId/prices'
      preLoaderRoute: typeof AuthedShellProductsIdVariantsVariantIdPricesRouteRouteImport
      parentRoute: typeof AuthedShellProductsIdVariantsVariantIdRouteRoute
    }
    '/_authed/settings/regions/$id/_detail/countries/': {
      id: '/_authed/settings/regions/$id/_detail/countries/'
      path: '/countries'
      fullPath: '/settings/regions/$id/countries/'
      preLoaderRoute: typeof AuthedSettingsRegionsIdDetailCountriesIndexRouteImport
      parentRoute: typeof AuthedSettingsRegionsIdDetailRouteRoute
    }
    '/_authed/settings/regions/$id/_detail/countries/$code': {
      id: '/_authed/settings/regions/$id/_detail/countries/$code'
      path: '/countries/$code'
      fullPath: '/settings/regions/$id/countries/$code'
      preLoaderRoute: typeof AuthedSettingsRegionsIdDetailCountriesCodeRouteImport
      parentRoute: typeof AuthedSettingsRegionsIdDetailRouteRoute
    }
    '/_authed/_shell/products/$id/_detail/images/$imageId/variants': {
      id: '/_authed/_shell/products/$id/_detail/images/$imageId/variants'
      path: '/images/$imageId/variants'
      fullPath: '/products/$id/images/$imageId/variants'
      preLoaderRoute: typeof AuthedShellProductsIdDetailImagesImageIdVariantsRouteImport
      parentRoute: typeof AuthedShellProductsIdDetailRouteRoute
    }
  }
}

interface AuthedShellOrdersIdDetailRouteRouteChildren {
  AuthedShellOrdersIdDetailIndexRoute: typeof AuthedShellOrdersIdDetailIndexRoute
}

const AuthedShellOrdersIdDetailRouteRouteChildren: AuthedShellOrdersIdDetailRouteRouteChildren =
  {
    AuthedShellOrdersIdDetailIndexRoute: AuthedShellOrdersIdDetailIndexRoute,
  }

const AuthedShellOrdersIdDetailRouteRouteWithChildren =
  AuthedShellOrdersIdDetailRouteRoute._addFileChildren(
    AuthedShellOrdersIdDetailRouteRouteChildren,
  )

interface AuthedShellOrdersIdRouteRouteChildren {
  AuthedShellOrdersIdDetailRouteRoute: typeof AuthedShellOrdersIdDetailRouteRouteWithChildren
}

const AuthedShellOrdersIdRouteRouteChildren: AuthedShellOrdersIdRouteRouteChildren =
  {
    AuthedShellOrdersIdDetailRouteRoute:
      AuthedShellOrdersIdDetailRouteRouteWithChildren,
  }

const AuthedShellOrdersIdRouteRouteWithChildren =
  AuthedShellOrdersIdRouteRoute._addFileChildren(
    AuthedShellOrdersIdRouteRouteChildren,
  )

interface AuthedShellOrdersRouteRouteChildren {
  AuthedShellOrdersIdRouteRoute: typeof AuthedShellOrdersIdRouteRouteWithChildren
  AuthedShellOrdersIndexRoute: typeof AuthedShellOrdersIndexRoute
}

const AuthedShellOrdersRouteRouteChildren: AuthedShellOrdersRouteRouteChildren =
  {
    AuthedShellOrdersIdRouteRoute: AuthedShellOrdersIdRouteRouteWithChildren,
    AuthedShellOrdersIndexRoute: AuthedShellOrdersIndexRoute,
  }

const AuthedShellOrdersRouteRouteWithChildren =
  AuthedShellOrdersRouteRoute._addFileChildren(
    AuthedShellOrdersRouteRouteChildren,
  )

interface AuthedShellProductOptionsIdDetailRouteRouteChildren {
  AuthedShellProductOptionsIdDetailEditRoute: typeof AuthedShellProductOptionsIdDetailEditRoute
  AuthedShellProductOptionsIdDetailIndexRoute: typeof AuthedShellProductOptionsIdDetailIndexRoute
}

const AuthedShellProductOptionsIdDetailRouteRouteChildren: AuthedShellProductOptionsIdDetailRouteRouteChildren =
  {
    AuthedShellProductOptionsIdDetailEditRoute:
      AuthedShellProductOptionsIdDetailEditRoute,
    AuthedShellProductOptionsIdDetailIndexRoute:
      AuthedShellProductOptionsIdDetailIndexRoute,
  }

const AuthedShellProductOptionsIdDetailRouteRouteWithChildren =
  AuthedShellProductOptionsIdDetailRouteRoute._addFileChildren(
    AuthedShellProductOptionsIdDetailRouteRouteChildren,
  )

interface AuthedShellProductOptionsIdRouteRouteChildren {
  AuthedShellProductOptionsIdDetailRouteRoute: typeof AuthedShellProductOptionsIdDetailRouteRouteWithChildren
}

const AuthedShellProductOptionsIdRouteRouteChildren: AuthedShellProductOptionsIdRouteRouteChildren =
  {
    AuthedShellProductOptionsIdDetailRouteRoute:
      AuthedShellProductOptionsIdDetailRouteRouteWithChildren,
  }

const AuthedShellProductOptionsIdRouteRouteWithChildren =
  AuthedShellProductOptionsIdRouteRoute._addFileChildren(
    AuthedShellProductOptionsIdRouteRouteChildren,
  )

interface AuthedShellProductOptionsRouteRouteChildren {
  AuthedShellProductOptionsIdRouteRoute: typeof AuthedShellProductOptionsIdRouteRouteWithChildren
  AuthedShellProductOptionsCreateRoute: typeof AuthedShellProductOptionsCreateRoute
  AuthedShellProductOptionsIndexRoute: typeof AuthedShellProductOptionsIndexRoute
}

const AuthedShellProductOptionsRouteRouteChildren: AuthedShellProductOptionsRouteRouteChildren =
  {
    AuthedShellProductOptionsIdRouteRoute:
      AuthedShellProductOptionsIdRouteRouteWithChildren,
    AuthedShellProductOptionsCreateRoute: AuthedShellProductOptionsCreateRoute,
    AuthedShellProductOptionsIndexRoute: AuthedShellProductOptionsIndexRoute,
  }

const AuthedShellProductOptionsRouteRouteWithChildren =
  AuthedShellProductOptionsRouteRoute._addFileChildren(
    AuthedShellProductOptionsRouteRouteChildren,
  )

interface AuthedShellProductsIdDetailRouteRouteChildren {
  AuthedShellProductsIdDetailEditRoute: typeof AuthedShellProductsIdDetailEditRoute
  AuthedShellProductsIdDetailMediaRoute: typeof AuthedShellProductsIdDetailMediaRoute
  AuthedShellProductsIdDetailOptionsRoute: typeof AuthedShellProductsIdDetailOptionsRoute
  AuthedShellProductsIdDetailIndexRoute: typeof AuthedShellProductsIdDetailIndexRoute
  AuthedShellProductsIdDetailImagesImageIdVariantsRoute: typeof AuthedShellProductsIdDetailImagesImageIdVariantsRoute
}

const AuthedShellProductsIdDetailRouteRouteChildren: AuthedShellProductsIdDetailRouteRouteChildren =
  {
    AuthedShellProductsIdDetailEditRoute: AuthedShellProductsIdDetailEditRoute,
    AuthedShellProductsIdDetailMediaRoute:
      AuthedShellProductsIdDetailMediaRoute,
    AuthedShellProductsIdDetailOptionsRoute:
      AuthedShellProductsIdDetailOptionsRoute,
    AuthedShellProductsIdDetailIndexRoute:
      AuthedShellProductsIdDetailIndexRoute,
    AuthedShellProductsIdDetailImagesImageIdVariantsRoute:
      AuthedShellProductsIdDetailImagesImageIdVariantsRoute,
  }

const AuthedShellProductsIdDetailRouteRouteWithChildren =
  AuthedShellProductsIdDetailRouteRoute._addFileChildren(
    AuthedShellProductsIdDetailRouteRouteChildren,
  )

interface AuthedShellProductsIdVariantsVariantIdRouteRouteChildren {
  AuthedShellProductsIdVariantsVariantIdPricesRouteRoute: typeof AuthedShellProductsIdVariantsVariantIdPricesRouteRoute
  AuthedShellProductsIdVariantsVariantIdEditRoute: typeof AuthedShellProductsIdVariantsVariantIdEditRoute
  AuthedShellProductsIdVariantsVariantIdMediaRoute: typeof AuthedShellProductsIdVariantsVariantIdMediaRoute
}

const AuthedShellProductsIdVariantsVariantIdRouteRouteChildren: AuthedShellProductsIdVariantsVariantIdRouteRouteChildren =
  {
    AuthedShellProductsIdVariantsVariantIdPricesRouteRoute:
      AuthedShellProductsIdVariantsVariantIdPricesRouteRoute,
    AuthedShellProductsIdVariantsVariantIdEditRoute:
      AuthedShellProductsIdVariantsVariantIdEditRoute,
    AuthedShellProductsIdVariantsVariantIdMediaRoute:
      AuthedShellProductsIdVariantsVariantIdMediaRoute,
  }

const AuthedShellProductsIdVariantsVariantIdRouteRouteWithChildren =
  AuthedShellProductsIdVariantsVariantIdRouteRoute._addFileChildren(
    AuthedShellProductsIdVariantsVariantIdRouteRouteChildren,
  )

interface AuthedShellProductsIdRouteRouteChildren {
  AuthedShellProductsIdDetailRouteRoute: typeof AuthedShellProductsIdDetailRouteRouteWithChildren
  AuthedShellProductsIdVariantsVariantIdRouteRoute: typeof AuthedShellProductsIdVariantsVariantIdRouteRouteWithChildren
  AuthedShellProductsIdVariantsCreateRoute: typeof AuthedShellProductsIdVariantsCreateRoute
}

const AuthedShellProductsIdRouteRouteChildren: AuthedShellProductsIdRouteRouteChildren =
  {
    AuthedShellProductsIdDetailRouteRoute:
      AuthedShellProductsIdDetailRouteRouteWithChildren,
    AuthedShellProductsIdVariantsVariantIdRouteRoute:
      AuthedShellProductsIdVariantsVariantIdRouteRouteWithChildren,
    AuthedShellProductsIdVariantsCreateRoute:
      AuthedShellProductsIdVariantsCreateRoute,
  }

const AuthedShellProductsIdRouteRouteWithChildren =
  AuthedShellProductsIdRouteRoute._addFileChildren(
    AuthedShellProductsIdRouteRouteChildren,
  )

interface AuthedShellProductsRouteRouteChildren {
  AuthedShellProductsIdRouteRoute: typeof AuthedShellProductsIdRouteRouteWithChildren
  AuthedShellProductsCreateRoute: typeof AuthedShellProductsCreateRoute
  AuthedShellProductsIndexRoute: typeof AuthedShellProductsIndexRoute
}

const AuthedShellProductsRouteRouteChildren: AuthedShellProductsRouteRouteChildren =
  {
    AuthedShellProductsIdRouteRoute:
      AuthedShellProductsIdRouteRouteWithChildren,
    AuthedShellProductsCreateRoute: AuthedShellProductsCreateRoute,
    AuthedShellProductsIndexRoute: AuthedShellProductsIndexRoute,
  }

const AuthedShellProductsRouteRouteWithChildren =
  AuthedShellProductsRouteRoute._addFileChildren(
    AuthedShellProductsRouteRouteChildren,
  )

interface AuthedShellRouteRouteChildren {
  AuthedShellOrdersRouteRoute: typeof AuthedShellOrdersRouteRouteWithChildren
  AuthedShellProductOptionsRouteRoute: typeof AuthedShellProductOptionsRouteRouteWithChildren
  AuthedShellProductsRouteRoute: typeof AuthedShellProductsRouteRouteWithChildren
  AuthedShellCustomersRoute: typeof AuthedShellCustomersRoute
  AuthedShellIndexRoute: typeof AuthedShellIndexRoute
}

const AuthedShellRouteRouteChildren: AuthedShellRouteRouteChildren = {
  AuthedShellOrdersRouteRoute: AuthedShellOrdersRouteRouteWithChildren,
  AuthedShellProductOptionsRouteRoute:
    AuthedShellProductOptionsRouteRouteWithChildren,
  AuthedShellProductsRouteRoute: AuthedShellProductsRouteRouteWithChildren,
  AuthedShellCustomersRoute: AuthedShellCustomersRoute,
  AuthedShellIndexRoute: AuthedShellIndexRoute,
}

const AuthedShellRouteRouteWithChildren =
  AuthedShellRouteRoute._addFileChildren(AuthedShellRouteRouteChildren)

interface AuthedSettingsRegionsIdDetailRouteRouteChildren {
  AuthedSettingsRegionsIdDetailEditRoute: typeof AuthedSettingsRegionsIdDetailEditRoute
  AuthedSettingsRegionsIdDetailIndexRoute: typeof AuthedSettingsRegionsIdDetailIndexRoute
  AuthedSettingsRegionsIdDetailCountriesCodeRoute: typeof AuthedSettingsRegionsIdDetailCountriesCodeRoute
  AuthedSettingsRegionsIdDetailCountriesIndexRoute: typeof AuthedSettingsRegionsIdDetailCountriesIndexRoute
}

const AuthedSettingsRegionsIdDetailRouteRouteChildren: AuthedSettingsRegionsIdDetailRouteRouteChildren =
  {
    AuthedSettingsRegionsIdDetailEditRoute:
      AuthedSettingsRegionsIdDetailEditRoute,
    AuthedSettingsRegionsIdDetailIndexRoute:
      AuthedSettingsRegionsIdDetailIndexRoute,
    AuthedSettingsRegionsIdDetailCountriesCodeRoute:
      AuthedSettingsRegionsIdDetailCountriesCodeRoute,
    AuthedSettingsRegionsIdDetailCountriesIndexRoute:
      AuthedSettingsRegionsIdDetailCountriesIndexRoute,
  }

const AuthedSettingsRegionsIdDetailRouteRouteWithChildren =
  AuthedSettingsRegionsIdDetailRouteRoute._addFileChildren(
    AuthedSettingsRegionsIdDetailRouteRouteChildren,
  )

interface AuthedSettingsRegionsIdRouteRouteChildren {
  AuthedSettingsRegionsIdDetailRouteRoute: typeof AuthedSettingsRegionsIdDetailRouteRouteWithChildren
}

const AuthedSettingsRegionsIdRouteRouteChildren: AuthedSettingsRegionsIdRouteRouteChildren =
  {
    AuthedSettingsRegionsIdDetailRouteRoute:
      AuthedSettingsRegionsIdDetailRouteRouteWithChildren,
  }

const AuthedSettingsRegionsIdRouteRouteWithChildren =
  AuthedSettingsRegionsIdRouteRoute._addFileChildren(
    AuthedSettingsRegionsIdRouteRouteChildren,
  )

interface AuthedSettingsRegionsRouteRouteChildren {
  AuthedSettingsRegionsIdRouteRoute: typeof AuthedSettingsRegionsIdRouteRouteWithChildren
  AuthedSettingsRegionsCreateRoute: typeof AuthedSettingsRegionsCreateRoute
  AuthedSettingsRegionsIndexRoute: typeof AuthedSettingsRegionsIndexRoute
}

const AuthedSettingsRegionsRouteRouteChildren: AuthedSettingsRegionsRouteRouteChildren =
  {
    AuthedSettingsRegionsIdRouteRoute:
      AuthedSettingsRegionsIdRouteRouteWithChildren,
    AuthedSettingsRegionsCreateRoute: AuthedSettingsRegionsCreateRoute,
    AuthedSettingsRegionsIndexRoute: AuthedSettingsRegionsIndexRoute,
  }

const AuthedSettingsRegionsRouteRouteWithChildren =
  AuthedSettingsRegionsRouteRoute._addFileChildren(
    AuthedSettingsRegionsRouteRouteChildren,
  )

interface AuthedSettingsStoreRouteRouteChildren {
  AuthedSettingsStoreCurrenciesRoute: typeof AuthedSettingsStoreCurrenciesRoute
  AuthedSettingsStoreEditRoute: typeof AuthedSettingsStoreEditRoute
  AuthedSettingsStoreIndexRoute: typeof AuthedSettingsStoreIndexRoute
}

const AuthedSettingsStoreRouteRouteChildren: AuthedSettingsStoreRouteRouteChildren =
  {
    AuthedSettingsStoreCurrenciesRoute: AuthedSettingsStoreCurrenciesRoute,
    AuthedSettingsStoreEditRoute: AuthedSettingsStoreEditRoute,
    AuthedSettingsStoreIndexRoute: AuthedSettingsStoreIndexRoute,
  }

const AuthedSettingsStoreRouteRouteWithChildren =
  AuthedSettingsStoreRouteRoute._addFileChildren(
    AuthedSettingsStoreRouteRouteChildren,
  )

interface AuthedSettingsUsersRouteRouteChildren {
  AuthedSettingsUsersInviteRoute: typeof AuthedSettingsUsersInviteRoute
}

const AuthedSettingsUsersRouteRouteChildren: AuthedSettingsUsersRouteRouteChildren =
  {
    AuthedSettingsUsersInviteRoute: AuthedSettingsUsersInviteRoute,
  }

const AuthedSettingsUsersRouteRouteWithChildren =
  AuthedSettingsUsersRouteRoute._addFileChildren(
    AuthedSettingsUsersRouteRouteChildren,
  )

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsRegionsRouteRoute: typeof AuthedSettingsRegionsRouteRouteWithChildren
  AuthedSettingsStoreRouteRoute: typeof AuthedSettingsStoreRouteRouteWithChildren
  AuthedSettingsUsersRouteRoute: typeof AuthedSettingsUsersRouteRouteWithChildren
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsRegionsRouteRoute: AuthedSettingsRegionsRouteRouteWithChildren,
  AuthedSettingsStoreRouteRoute: AuthedSettingsStoreRouteRouteWithChildren,
  AuthedSettingsUsersRouteRoute: AuthedSettingsUsersRouteRouteWithChildren,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedShellRouteRoute: typeof AuthedShellRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedShellRouteRoute: AuthedShellRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicInviteRoute: typeof PublicInviteRoute
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicInviteRoute: PublicInviteRoute,
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
