import type { RouteDefinition } from '@framework/http/types.js'
import { searchable, Tags } from '@framework/http/types.js'
import type { ProductDTO, ProductVariantDTO } from '../../../core/types/product/common.js'
import * as imageVariantBatchRoutes from './[id]/images/[imageId]/variants/batch/route.js'
import * as productOptionRoutes from './[id]/options/route.js'
import * as productByIdRoutes from './[id]/route.js'
import * as variantImageBatchRoutes from './[id]/variants/[variantId]/images/batch/route.js'
import * as variantPricesRoutes from './[id]/variants/[variantId]/prices/route.js'
import * as variantByIdRoutes from './[id]/variants/[variantId]/route.js'
import * as variantRoutes from './[id]/variants/route.js'
import * as productRoutes from './route.js'

export default [
  {
    method: 'GET',
    matcher: '/admin/products',
    handler: productRoutes.GET,
    input: productRoutes.GetInput,
    searchableColumns: searchable<ProductDTO>('title', 'handle'),
    operationId: 'listProducts',
    summary: 'List products',
    tags: [Tags.PRODUCTS],
    output: productRoutes.GetOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/products',
    handler: productRoutes.POST,
    input: productRoutes.PostInput,
    operationId: 'createProduct',
    summary: 'Create a product',
    tags: [Tags.PRODUCTS],
    output: productRoutes.PostOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/products/:id',
    handler: productByIdRoutes.GET,
    input: productByIdRoutes.GetInput,
    operationId: 'getProduct',
    summary: 'Retrieve a product',
    tags: [Tags.PRODUCTS],
    output: productByIdRoutes.GetOutput,
  },
  {
    method: 'PATCH',
    matcher: '/admin/products/:id',
    handler: productByIdRoutes.PATCH,
    input: productByIdRoutes.PatchInput,
    operationId: 'updateProduct',
    summary: 'Update a product',
    tags: [Tags.PRODUCTS],
    output: productByIdRoutes.PatchOutput,
  },
  {
    method: 'DELETE',
    matcher: '/admin/products/:id',
    handler: productByIdRoutes.DELETE,
    input: productByIdRoutes.DeleteInput,
    operationId: 'deleteProduct',
    summary: 'Delete a product',
    tags: [Tags.PRODUCTS],
    output: productByIdRoutes.DeleteOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/products/:id/options',
    handler: productOptionRoutes.GET,
    input: productOptionRoutes.GetInput,
    operationId: 'getProductOptions',
    summary: 'List options for a product',
    tags: [Tags.PRODUCT_OPTIONS],
    output: productOptionRoutes.GetOutput,
  },
  {
    method: 'PUT',
    matcher: '/admin/products/:id/options',
    handler: productOptionRoutes.PUT,
    input: productOptionRoutes.PutInput,
    operationId: 'setProductOptions',
    summary: 'Set options for a product',
    tags: [Tags.PRODUCT_OPTIONS],
    output: productOptionRoutes.PutOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/products/:id/variants',
    handler: variantRoutes.GET,
    input: variantRoutes.GetInput,
    searchableColumns: searchable<ProductVariantDTO>('title', 'sku'),
    operationId: 'listProductVariants',
    summary: 'List product variants',
    tags: [Tags.PRODUCT_VARIANTS],
    output: variantRoutes.GetOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/products/:id/variants',
    handler: variantRoutes.POST,
    input: variantRoutes.PostInput,
    operationId: 'createProductVariant',
    summary: 'Create a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    output: variantRoutes.PostOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/products/:id/variants/:variantId',
    handler: variantByIdRoutes.GET,
    input: variantByIdRoutes.GetInput,
    operationId: 'getProductVariant',
    summary: 'Retrieve a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    output: variantByIdRoutes.GetOutput,
  },
  {
    method: 'PATCH',
    matcher: '/admin/products/:id/variants/:variantId',
    handler: variantByIdRoutes.PATCH,
    input: variantByIdRoutes.PatchInput,
    operationId: 'updateProductVariant',
    summary: 'Update a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    output: variantByIdRoutes.PatchOutput,
  },
  {
    method: 'PUT',
    matcher: '/admin/products/:id/variants/:variantId/prices',
    handler: variantPricesRoutes.PUT,
    input: variantPricesRoutes.PutInput,
    operationId: 'updateVariantPrices',
    summary: 'Update variant prices',
    tags: [Tags.PRODUCT_VARIANTS],
    output: variantPricesRoutes.PutOutput,
  },
  {
    method: 'DELETE',
    matcher: '/admin/products/:id/variants/:variantId',
    handler: variantByIdRoutes.DELETE,
    input: variantByIdRoutes.DeleteInput,
    operationId: 'deleteProductVariant',
    summary: 'Delete a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    output: variantByIdRoutes.DeleteOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/products/:id/images/:imageId/variants/batch',
    handler: imageVariantBatchRoutes.POST,
    input: imageVariantBatchRoutes.PostInput,
    operationId: 'batchImageVariants',
    summary: 'Add or remove variants for a product image',
    tags: [Tags.PRODUCTS],
    output: imageVariantBatchRoutes.PostOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/products/:id/variants/:variantId/images/batch',
    handler: variantImageBatchRoutes.POST,
    input: variantImageBatchRoutes.PostInput,
    operationId: 'batchVariantImages',
    summary: 'Add or remove images for a product variant',
    tags: [Tags.PRODUCT_VARIANTS],
    output: variantImageBatchRoutes.PostOutput,
  },
] satisfies RouteDefinition[]
