import type { RouteDefinition } from '@framework/http/types.js'
import { searchable, Tags } from '@framework/http/types.js'
import type { RegionDTO } from '../../../core/types/region/common.js'
import * as regionCountryRoutes from './[id]/countries/[code]/route.js'
import * as regionCountriesRoutes from './[id]/countries/route.js'
import * as regionByIdRoutes from './[id]/route.js'
import * as regionRoutes from './route.js'

export default [
  {
    method: 'GET',
    matcher: '/admin/regions',
    handler: regionRoutes.GET,
    input: regionRoutes.GetInput,
    searchableColumns: searchable<RegionDTO>('name'),
    permissions: ['region.read'],
    operationId: 'listRegions',
    summary: 'List regions',
    tags: [Tags.REGIONS],
    output: regionRoutes.GetOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/regions',
    handler: regionRoutes.POST,
    input: regionRoutes.PostInput,
    permissions: ['region.create'],
    operationId: 'createRegion',
    summary: 'Create a region',
    tags: [Tags.REGIONS],
    throws: regionRoutes.PostThrows,
    output: regionRoutes.PostOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/regions/:id',
    handler: regionByIdRoutes.GET,
    input: regionByIdRoutes.GetInput,
    permissions: ['region.read'],
    operationId: 'getRegion',
    summary: 'Retrieve a region',
    tags: [Tags.REGIONS],
    output: regionByIdRoutes.GetOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/regions/:id',
    handler: regionByIdRoutes.POST,
    input: regionByIdRoutes.PostInput,
    permissions: ['region.update'],
    operationId: 'updateRegion',
    summary: 'Update a region',
    tags: [Tags.REGIONS],
    throws: regionByIdRoutes.PostThrows,
    output: regionByIdRoutes.PostOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/regions/:id/countries',
    handler: regionCountriesRoutes.POST,
    input: regionCountriesRoutes.PostInput,
    permissions: ['region.update'],
    operationId: 'assignRegionCountries',
    summary: 'Assign countries to a region',
    tags: [Tags.REGIONS],
    throws: regionCountriesRoutes.PostThrows,
    output: regionCountriesRoutes.PostOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/regions/:id/countries/:code',
    handler: regionCountryRoutes.POST,
    input: regionCountryRoutes.PostInput,
    permissions: ['region.update'],
    operationId: 'updateRegionCountryLocale',
    summary: "Update a country's locale",
    tags: [Tags.REGIONS],
    throws: regionCountryRoutes.PostThrows,
    output: regionCountryRoutes.PostOutput,
  },
  {
    method: 'DELETE',
    matcher: '/admin/regions/:id/countries/:code',
    handler: regionCountryRoutes.DELETE,
    input: regionCountryRoutes.DeleteInput,
    permissions: ['region.update'],
    operationId: 'removeRegionCountry',
    summary: 'Remove a country from a region',
    tags: [Tags.REGIONS],
    throws: regionCountryRoutes.DeleteThrows,
    output: regionCountryRoutes.DeleteOutput,
  },
] satisfies RouteDefinition[]
