export const Modules = {
  AUTH: 'auth',
  USER: 'user',
  CUSTOMER: 'customer',
  CART: 'cart',
  ORDER: 'order',
  PAYMENT: 'payment',
  PROMOTION: 'promotion',
  INVENTORY: 'inventory',
  PRICING: 'pricing',
  PRODUCT: 'product',
  FULFILLMENT: 'fulfillment',
  NOTIFICATION: 'notification',
  FILE: 'file',
  REGION: 'region',
  STORE: 'store',
} as const
