/**
 * Writes the drizzle schema: one `export *` per table-declaring file in the backend.
 *
 * Drizzle needs every table and relation as one namespace — `schema.type.ts` turns it into
 * `Database`, and `getDb()` returns an instance aware of it. That namespace used to be a
 * hand-written `schema.ts` over fourteen hand-written barrels. All fifteen are gone: a module names
 * its tables in the `models` object of its `Module()` definition, which is the list
 * `buildCascadeGraph` reads and `model-reaches-cascade-graph` checks, and the schema is enumerated
 * from the files instead.
 *
 * Generated rather than hand-written because the list is pure enumeration, and because the
 * hand-written version had drifted: it re-exported five of the seven link definitions and one of
 * those type-only, so two link tables and three sets of relations were absent from the schema with
 * nothing to say whether that was a decision or an omission.
 *
 * The artifact is committed, like the two registries, so every environment runs the identical file
 * and workerd needs no directory scan. `--check` fails the verify gate when it drifts.
 */

import type { Dirent } from 'node:fs'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const RED = '\x1b[0;31m'
const GREEN = '\x1b[0;32m'
const YELLOW = '\x1b[0;33m'
const DIM = '\x1b[2m'
const BOLD = '\x1b[1m'
const RESET = '\x1b[0m'

const BACKEND_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = join(BACKEND_ROOT, 'src')
const MODULES_DIR = join(SRC_DIR, 'modules')
const LINK_DEFINITIONS_DIR = join(SRC_DIR, 'link-modules/definitions')
const OUTPUT = join(SRC_DIR, 'schema.gen.ts')

/**
 * Every model file, as a module specifier relative to `src/`. Sorted by specifier so the output is
 * a function of the source tree and not of readdir order, which differs across filesystems.
 */
function specifiersIn(directory: string): string[] {
  let entries: Dirent[]
  try {
    entries = readdirSync(directory, { withFileTypes: true })
  } catch {
    // A module that owns no tables has no models/ at all. `file` is the one today.
    return []
  }

  return entries.flatMap((entry) => {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) return specifiersIn(path)
    if (!entry.name.endsWith('.ts')) return []
    return [`./${relative(SRC_DIR, path).replace(/\.ts$/, '.js')}`]
  })
}

/**
 * Every file that may declare a table, as a module specifier relative to `src/`. Sorted by
 * specifier so the output is a function of the source tree and not of readdir order, which differs
 * across filesystems.
 */
function schemaSpecifiers(): string[] {
  const modules = readdirSync(MODULES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .flatMap((entry) => specifiersIn(join(MODULES_DIR, entry.name, 'models')))

  return [...modules, ...specifiersIn(LINK_DEFINITIONS_DIR)].sort()
}

function render(specifiers: string[]): string {
  return [
    '// Generated by `pnpm --filter backend run schema:generate`. Do not edit.',
    '//',
    '// The drizzle schema: one line per file under src/modules/*/models/ and',
    '// src/link-modules/definitions/. Passed to drizzle via DRIZZLE_OPTIONS, so getDb() returns a',
    '// schema-aware instance.',
    '',
    ...specifiers.map((specifier) => `export * from '${specifier}'`),
    '',
  ].join('\n')
}

/** Absent on the first run, and an empty string then differs from any render, which is the right answer. */
function existingOutput(): string {
  try {
    return readFileSync(OUTPUT, 'utf8')
  } catch {
    return ''
  }
}

const specifiers = schemaSpecifiers()
const rendered = render(specifiers)
const existing = existingOutput()
const count = specifiers.length

if (process.argv.includes('--check')) {
  if (existing !== rendered) {
    console.info('')
    console.info(`${RED}${BOLD}schema${RESET} ${DIM}${'━'.repeat(70)}${RESET}`)
    console.info('')
    console.info(
      `  ${RED}✖${RESET} src/schema.gen.ts is out of date with src/modules/*/models/ and src/link-modules/definitions/.`,
    )
    console.info(`    ${DIM}${count} model files found in the source tree.${RESET}`)
    console.info(`    ${YELLOW}→${RESET} run \`pnpm --filter backend run schema:generate\` and commit the result`)
    console.info('')
    process.exit(1)
  }
  console.info(`${GREEN}✔${RESET} schema — schema.gen.ts matches the source tree. ${DIM}${count} files.${RESET}`)
} else if (existing === rendered) {
  console.info(`${GREEN}✔${RESET} schema — already current. ${DIM}${count} files.${RESET}`)
} else {
  writeFileSync(OUTPUT, rendered)
  console.info(`${GREEN}✔${RESET} schema — wrote schema.gen.ts. ${DIM}${count} files.${RESET}`)
}
