import type { ExportTemplate } from '../src/build-icons/types.ts'

/**
 * Inline the source SVG as a data URI so hovering the import in an editor previews the mark.
 * Brand marks are solid fills, so the preview only needs a light plate behind it.
 */
const base64SVG = (svgContents: string) =>
  Buffer.from(svgContents.replace('<svg', '<svg style="background-color: #fff; border-radius: 2px"')).toString('base64')

export const exportTemplate: ExportTemplate = async ({ componentName, iconName, label, children, getSvg }) => {
  const svgBase64 = base64SVG(await getSvg())

  return `// Generated by \`npm run --workspace=@proteus/icons build:icons\`. Do not edit.
import { createIcon } from '../src/create-icon.ts'
import type { IconNode } from '../src/types.ts'

const iconNode: IconNode = ${JSON.stringify(children)}

/**
 * @component @name ${componentName}Icon
 * @description ${label || componentName} brand mark, rendered as an SVG element.
 *
 * @preview ![img](data:image/svg+xml;base64,${svgBase64})
 * @source assets/${iconName}.svg
 */
export const ${componentName}Icon = createIcon('${componentName}', iconNode)
`
}
