import type { RouteDefinition } from '@framework/http/types.js'
import { Tags } from '@framework/http/types.js'
import * as userRoleRoutes from './[id]/roles/route.js'
import * as userByIdRoutes from './[id]/route.js'
import * as meRoutes from './me/route.js'
import * as userRoutes from './route.js'

export default [
  {
    method: 'GET',
    matcher: '/admin/users/me',
    handler: meRoutes.GET,
    throws: meRoutes.GetThrows,
    operationId: 'getMe',
    summary: 'Retrieve the authenticated user',
    tags: [Tags.USERS],
    output: meRoutes.GetOutput,
  },
  {
    method: 'PATCH',
    matcher: '/admin/users/me',
    handler: meRoutes.PATCH,
    input: meRoutes.PatchInput,
    throws: meRoutes.PatchThrows,
    operationId: 'updateMe',
    summary: 'Update the authenticated user',
    tags: [Tags.USERS],
    output: meRoutes.PatchOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/users',
    handler: userRoutes.GET,
    input: userRoutes.GetInput,
    permissions: ['user.read'],
    operationId: 'listUsers',
    summary: 'List users',
    tags: [Tags.USERS],
    output: userRoutes.GetOutput,
  },
  {
    method: 'POST',
    matcher: '/admin/users',
    handler: userRoutes.POST,
    input: userRoutes.PostInput,
    permissions: ['user.create'],
    operationId: 'createUser',
    summary: 'Create a user',
    tags: [Tags.USERS],
    output: userRoutes.PostOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/users/:id',
    handler: userByIdRoutes.GET,
    input: userByIdRoutes.GetInput,
    permissions: ['user.read'],
    operationId: 'getUser',
    summary: 'Retrieve a user',
    tags: [Tags.USERS],
    output: userByIdRoutes.GetOutput,
  },
  {
    method: 'PATCH',
    matcher: '/admin/users/:id',
    handler: userByIdRoutes.PATCH,
    input: userByIdRoutes.PatchInput,
    permissions: ['user.update'],
    operationId: 'updateUser',
    summary: 'Update a user',
    tags: [Tags.USERS],
    output: userByIdRoutes.PatchOutput,
  },
  {
    method: 'DELETE',
    matcher: '/admin/users/:id',
    handler: userByIdRoutes.DELETE,
    input: userByIdRoutes.DeleteInput,
    permissions: ['user.delete'],
    operationId: 'deleteUser',
    summary: 'Delete a user',
    tags: [Tags.USERS],
    output: userByIdRoutes.DeleteOutput,
  },
  {
    method: 'GET',
    matcher: '/admin/users/:id/roles',
    handler: userRoleRoutes.GET,
    input: userRoleRoutes.GetInput,
    permissions: ['access-control.assignment.read'],
    operationId: 'listUserRoles',
    summary: "List a user's roles",
    tags: [Tags.USERS],
    output: userRoleRoutes.GetOutput,
  },
  {
    method: 'PUT',
    matcher: '/admin/users/:id/roles',
    handler: userRoleRoutes.PUT,
    input: userRoleRoutes.PutInput,
    permissions: ['access-control.assignment.write'],
    operationId: 'replaceUserRoles',
    summary: "Replace a user's roles",
    tags: [Tags.USERS],
    throws: userRoleRoutes.PutThrows,
    output: userRoleRoutes.PutOutput,
  },
] satisfies RouteDefinition[]
