// GENERATED by `npm run workflows:generate`. Do not edit — your change will be overwritten.
//
// Every workflow `src/workflows/` defines, as static imports, so the handler closures exist in the
// Worker process and `tsx --watch` has a module graph to reload from. `npm run verify` fails when
// this file drifts from the source tree.

import type { WorkflowDefinition } from '../core/workflows/types.js'
import { requestPasswordResetWorkflow } from '../workflows/auth/request-password-reset.js'
import { addToCartWorkflow } from '../workflows/cart/add-to-cart.js'
import { completeCartWorkflow } from '../workflows/cart/complete-cart.js'
import { confirmInventoryWorkflow } from '../workflows/cart/confirm-inventory-workflow.js'
import { transferCartCustomerWorkflow } from '../workflows/cart/transfer-cart-customer.js'
import { updateCartWorkflow } from '../workflows/cart/update-cart.js'
import { completeCustomerAuthWorkflow } from '../workflows/customer/complete-customer-auth.js'
import { createCustomerAccountWorkflow } from '../workflows/customer/create-customer-account.js'
import { deleteFilesWorkflow } from '../workflows/file/delete-files.js'
import { uploadFilesWorkflow } from '../workflows/file/upload-files.js'
import { cancelOrderWorkflow } from '../workflows/order/cancel-order.js'
import { createOrderFulfillmentWorkflow } from '../workflows/order/create-order-fulfillment.js'
import { createOrderShipmentWorkflow } from '../workflows/order/create-order-shipment.js'
import { markOrderDeliveredWorkflow } from '../workflows/order/mark-order-delivered.js'
import { createPaymentCollectionForCartWorkflow } from '../workflows/payment/create-payment-collection-for-cart.js'
import { repricePaymentSessionWorkflow } from '../workflows/payment/reprice-payment-session.js'
import { batchImageVariantsWorkflow } from '../workflows/product/batch-image-variants.js'
import { batchVariantImagesWorkflow } from '../workflows/product/batch-variant-images.js'
import { createProductVariantsWorkflow } from '../workflows/product/create-product-variants.js'
import { createProductWorkflow } from '../workflows/product/create-product.js'
import { deleteProductVariantWorkflow } from '../workflows/product/delete-product-variant.js'
import { setProductOptionsWorkflow } from '../workflows/product/set-product-options.js'
import { updateProductVariantWorkflow } from '../workflows/product/update-product-variant.js'
import { updateVariantPricesWorkflow } from '../workflows/product/update-variant-prices.js'
import { acceptInviteWorkflow } from '../workflows/user/accept-invite.js'
import { createInviteWorkflow } from '../workflows/user/create-invite.js'
import { resendInviteWorkflow } from '../workflows/user/resend-invite.js'

export const GENERATED_WORKFLOWS: WorkflowDefinition<never, unknown>[] = [
  requestPasswordResetWorkflow,
  addToCartWorkflow,
  completeCartWorkflow,
  confirmInventoryWorkflow,
  transferCartCustomerWorkflow,
  updateCartWorkflow,
  completeCustomerAuthWorkflow,
  createCustomerAccountWorkflow,
  deleteFilesWorkflow,
  uploadFilesWorkflow,
  cancelOrderWorkflow,
  createOrderFulfillmentWorkflow,
  createOrderShipmentWorkflow,
  markOrderDeliveredWorkflow,
  createPaymentCollectionForCartWorkflow,
  repricePaymentSessionWorkflow,
  batchImageVariantsWorkflow,
  batchVariantImagesWorkflow,
  createProductVariantsWorkflow,
  createProductWorkflow,
  deleteProductVariantWorkflow,
  setProductOptionsWorkflow,
  updateProductVariantWorkflow,
  updateVariantPricesWorkflow,
  acceptInviteWorkflow,
  createInviteWorkflow,
  resendInviteWorkflow,
]
