/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteRouteImport } from './routes/_checkout/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as CheckoutCheckoutRouteImport } from './routes/_checkout/checkout'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainAuthedRouteRouteImport } from './routes/_main/_authed/route'
import { Route as MainCartRouteImport } from './routes/_main/cart'
import { Route as MainForgotPasswordRouteImport } from './routes/_main/forgot-password'
import { Route as MainLoginRouteImport } from './routes/_main/login'
import { Route as MainProductsRouteRouteImport } from './routes/_main/products/route'
import { Route as MainResetPasswordRouteImport } from './routes/_main/reset-password'
import { Route as MainVerifyRouteImport } from './routes/_main/verify'
import { Route as MainAuthedAccountRouteImport } from './routes/_main/_authed/account'
import { Route as MainProductsIndexRouteImport } from './routes/_main/products/index'
import { Route as MainProductsProductIdRouteImport } from './routes/_main/products/$productId'

const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/_checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCheckoutRoute = CheckoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAuthedRouteRoute = MainAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCartRoute = MainCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainForgotPasswordRoute = MainForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductsRouteRoute = MainProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainResetPasswordRoute = MainResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainVerifyRoute = MainVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAuthedAccountRoute = MainAuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MainAuthedRouteRoute,
} as any)
const MainProductsIndexRoute = MainProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainProductsRouteRoute,
} as any)
const MainProductsProductIdRoute = MainProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => MainProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/products': typeof MainProductsRouteRouteWithChildren
  '/checkout': typeof CheckoutCheckoutRoute
  '/cart': typeof MainCartRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/login': typeof MainLoginRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/verify': typeof MainVerifyRoute
  '/account': typeof MainAuthedAccountRoute
  '/products/$productId': typeof MainProductsProductIdRoute
  '/products/': typeof MainProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/checkout': typeof CheckoutCheckoutRoute
  '/cart': typeof MainCartRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/login': typeof MainLoginRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/verify': typeof MainVerifyRoute
  '/account': typeof MainAuthedAccountRoute
  '/products/$productId': typeof MainProductsProductIdRoute
  '/products': typeof MainProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_checkout': typeof CheckoutRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/_authed': typeof MainAuthedRouteRouteWithChildren
  '/_main/products': typeof MainProductsRouteRouteWithChildren
  '/_checkout/checkout': typeof CheckoutCheckoutRoute
  '/_main/cart': typeof MainCartRoute
  '/_main/forgot-password': typeof MainForgotPasswordRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/reset-password': typeof MainResetPasswordRoute
  '/_main/verify': typeof MainVerifyRoute
  '/_main/': typeof MainIndexRoute
  '/_main/_authed/account': typeof MainAuthedAccountRoute
  '/_main/products/$productId': typeof MainProductsProductIdRoute
  '/_main/products/': typeof MainProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/checkout'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/account'
    | '/products/$productId'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/cart'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/verify'
    | '/account'
    | '/products/$productId'
    | '/products'
  id:
    | '__root__'
    | '/_checkout'
    | '/_main'
    | '/_main/_authed'
    | '/_main/products'
    | '/_checkout/checkout'
    | '/_main/cart'
    | '/_main/forgot-password'
    | '/_main/login'
    | '/_main/reset-password'
    | '/_main/verify'
    | '/_main/'
    | '/_main/_authed/account'
    | '/_main/products/$productId'
    | '/_main/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_checkout': {
      id: '/_checkout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_checkout/checkout': {
      id: '/_checkout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutCheckoutRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_authed': {
      id: '/_main/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAuthedRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/cart': {
      id: '/_main/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainCartRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/forgot-password': {
      id: '/_main/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof MainForgotPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/products': {
      id: '/_main/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof MainProductsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reset-password': {
      id: '/_main/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainResetPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/verify': {
      id: '/_main/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof MainVerifyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_authed/account': {
      id: '/_main/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof MainAuthedAccountRouteImport
      parentRoute: typeof MainAuthedRouteRoute
    }
    '/_main/products/': {
      id: '/_main/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof MainProductsIndexRouteImport
      parentRoute: typeof MainProductsRouteRoute
    }
    '/_main/products/$productId': {
      id: '/_main/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof MainProductsProductIdRouteImport
      parentRoute: typeof MainProductsRouteRoute
    }
  }
}

interface CheckoutRouteRouteChildren {
  CheckoutCheckoutRoute: typeof CheckoutCheckoutRoute
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutCheckoutRoute: CheckoutCheckoutRoute,
}

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren,
)

interface MainAuthedRouteRouteChildren {
  MainAuthedAccountRoute: typeof MainAuthedAccountRoute
}

const MainAuthedRouteRouteChildren: MainAuthedRouteRouteChildren = {
  MainAuthedAccountRoute: MainAuthedAccountRoute,
}

const MainAuthedRouteRouteWithChildren = MainAuthedRouteRoute._addFileChildren(
  MainAuthedRouteRouteChildren,
)

interface MainProductsRouteRouteChildren {
  MainProductsProductIdRoute: typeof MainProductsProductIdRoute
  MainProductsIndexRoute: typeof MainProductsIndexRoute
}

const MainProductsRouteRouteChildren: MainProductsRouteRouteChildren = {
  MainProductsProductIdRoute: MainProductsProductIdRoute,
  MainProductsIndexRoute: MainProductsIndexRoute,
}

const MainProductsRouteRouteWithChildren =
  MainProductsRouteRoute._addFileChildren(MainProductsRouteRouteChildren)

interface MainRouteRouteChildren {
  MainAuthedRouteRoute: typeof MainAuthedRouteRouteWithChildren
  MainProductsRouteRoute: typeof MainProductsRouteRouteWithChildren
  MainCartRoute: typeof MainCartRoute
  MainForgotPasswordRoute: typeof MainForgotPasswordRoute
  MainLoginRoute: typeof MainLoginRoute
  MainResetPasswordRoute: typeof MainResetPasswordRoute
  MainVerifyRoute: typeof MainVerifyRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuthedRouteRoute: MainAuthedRouteRouteWithChildren,
  MainProductsRouteRoute: MainProductsRouteRouteWithChildren,
  MainCartRoute: MainCartRoute,
  MainForgotPasswordRoute: MainForgotPasswordRoute,
  MainLoginRoute: MainLoginRoute,
  MainResetPasswordRoute: MainResetPasswordRoute,
  MainVerifyRoute: MainVerifyRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
