/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as CheckoutRouteRouteImport } from './routes/_checkout/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthVerifyRouteImport } from './routes/_auth/verify'
import { Route as CheckoutCheckoutRouteImport } from './routes/_checkout/checkout'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainAuthedRouteRouteImport } from './routes/_main/_authed/route'
import { Route as MainCartRouteImport } from './routes/_main/cart'
import { Route as MainProductsRouteRouteImport } from './routes/_main/products/route'
import { Route as MainProductsIndexRouteImport } from './routes/_main/products/index'
import { Route as MainProductsProductIdRouteImport } from './routes/_main/products/$productId'
import { Route as MainAuthedAccountIndexRouteImport } from './routes/_main/_authed/account/index'
import { Route as MainOrderOrderIdConfirmedRouteImport } from './routes/_main/order/$orderId/confirmed'
import { Route as MainAuthedAccountOrdersOrderIdRouteImport } from './routes/_main/_authed/account/orders/$orderId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/_checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRouteRoute,
} as any)
const CheckoutCheckoutRoute = CheckoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAuthedRouteRoute = MainAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCartRoute = MainCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductsRouteRoute = MainProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProductsIndexRoute = MainProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainProductsRouteRoute,
} as any)
const MainProductsProductIdRoute = MainProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => MainProductsRouteRoute,
} as any)
const MainAuthedAccountIndexRoute = MainAuthedAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => MainAuthedRouteRoute,
} as any)
const MainOrderOrderIdConfirmedRoute =
  MainOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainAuthedAccountOrdersOrderIdRoute =
  MainAuthedAccountOrdersOrderIdRouteImport.update({
    id: '/account/orders/$orderId',
    path: '/account/orders/$orderId',
    getParentRoute: () => MainAuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/products': typeof MainProductsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify': typeof AuthVerifyRoute
  '/checkout': typeof CheckoutCheckoutRoute
  '/cart': typeof MainCartRoute
  '/products/$productId': typeof MainProductsProductIdRoute
  '/products/': typeof MainProductsIndexRoute
  '/order/$orderId/confirmed': typeof MainOrderOrderIdConfirmedRoute
  '/account/': typeof MainAuthedAccountIndexRoute
  '/account/orders/$orderId': typeof MainAuthedAccountOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/verify': typeof AuthVerifyRoute
  '/checkout': typeof CheckoutCheckoutRoute
  '/cart': typeof MainCartRoute
  '/products/$productId': typeof MainProductsProductIdRoute
  '/products': typeof MainProductsIndexRoute
  '/order/$orderId/confirmed': typeof MainOrderOrderIdConfirmedRoute
  '/account': typeof MainAuthedAccountIndexRoute
  '/account/orders/$orderId': typeof MainAuthedAccountOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_checkout': typeof CheckoutRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/_authed': typeof MainAuthedRouteRouteWithChildren
  '/_main/products': typeof MainProductsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/_checkout/checkout': typeof CheckoutCheckoutRoute
  '/_main/cart': typeof MainCartRoute
  '/_main/': typeof MainIndexRoute
  '/_main/products/$productId': typeof MainProductsProductIdRoute
  '/_main/products/': typeof MainProductsIndexRoute
  '/_main/order/$orderId/confirmed': typeof MainOrderOrderIdConfirmedRoute
  '/_main/_authed/account/': typeof MainAuthedAccountIndexRoute
  '/_main/_authed/account/orders/$orderId': typeof MainAuthedAccountOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/checkout'
    | '/cart'
    | '/products/$productId'
    | '/products/'
    | '/order/$orderId/confirmed'
    | '/account/'
    | '/account/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/checkout'
    | '/cart'
    | '/products/$productId'
    | '/products'
    | '/order/$orderId/confirmed'
    | '/account'
    | '/account/orders/$orderId'
  id:
    | '__root__'
    | '/_auth'
    | '/_checkout'
    | '/_main'
    | '/_main/_authed'
    | '/_main/products'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_auth/verify'
    | '/_checkout/checkout'
    | '/_main/cart'
    | '/_main/'
    | '/_main/products/$productId'
    | '/_main/products/'
    | '/_main/order/$orderId/confirmed'
    | '/_main/_authed/account/'
    | '/_main/_authed/account/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_checkout': {
      id: '/_checkout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_checkout/checkout': {
      id: '/_checkout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutCheckoutRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_authed': {
      id: '/_main/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAuthedRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/cart': {
      id: '/_main/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof MainCartRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/products': {
      id: '/_main/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof MainProductsRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/products/': {
      id: '/_main/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof MainProductsIndexRouteImport
      parentRoute: typeof MainProductsRouteRoute
    }
    '/_main/products/$productId': {
      id: '/_main/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof MainProductsProductIdRouteImport
      parentRoute: typeof MainProductsRouteRoute
    }
    '/_main/_authed/account/': {
      id: '/_main/_authed/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof MainAuthedAccountIndexRouteImport
      parentRoute: typeof MainAuthedRouteRoute
    }
    '/_main/order/$orderId/confirmed': {
      id: '/_main/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/order/$orderId/confirmed'
      preLoaderRoute: typeof MainOrderOrderIdConfirmedRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_authed/account/orders/$orderId': {
      id: '/_main/_authed/account/orders/$orderId'
      path: '/account/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof MainAuthedAccountOrdersOrderIdRouteImport
      parentRoute: typeof MainAuthedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CheckoutRouteRouteChildren {
  CheckoutCheckoutRoute: typeof CheckoutCheckoutRoute
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutCheckoutRoute: CheckoutCheckoutRoute,
}

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren,
)

interface MainAuthedRouteRouteChildren {
  MainAuthedAccountIndexRoute: typeof MainAuthedAccountIndexRoute
  MainAuthedAccountOrdersOrderIdRoute: typeof MainAuthedAccountOrdersOrderIdRoute
}

const MainAuthedRouteRouteChildren: MainAuthedRouteRouteChildren = {
  MainAuthedAccountIndexRoute: MainAuthedAccountIndexRoute,
  MainAuthedAccountOrdersOrderIdRoute: MainAuthedAccountOrdersOrderIdRoute,
}

const MainAuthedRouteRouteWithChildren = MainAuthedRouteRoute._addFileChildren(
  MainAuthedRouteRouteChildren,
)

interface MainProductsRouteRouteChildren {
  MainProductsProductIdRoute: typeof MainProductsProductIdRoute
  MainProductsIndexRoute: typeof MainProductsIndexRoute
}

const MainProductsRouteRouteChildren: MainProductsRouteRouteChildren = {
  MainProductsProductIdRoute: MainProductsProductIdRoute,
  MainProductsIndexRoute: MainProductsIndexRoute,
}

const MainProductsRouteRouteWithChildren =
  MainProductsRouteRoute._addFileChildren(MainProductsRouteRouteChildren)

interface MainRouteRouteChildren {
  MainAuthedRouteRoute: typeof MainAuthedRouteRouteWithChildren
  MainProductsRouteRoute: typeof MainProductsRouteRouteWithChildren
  MainCartRoute: typeof MainCartRoute
  MainIndexRoute: typeof MainIndexRoute
  MainOrderOrderIdConfirmedRoute: typeof MainOrderOrderIdConfirmedRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuthedRouteRoute: MainAuthedRouteRouteWithChildren,
  MainProductsRouteRoute: MainProductsRouteRouteWithChildren,
  MainCartRoute: MainCartRoute,
  MainIndexRoute: MainIndexRoute,
  MainOrderOrderIdConfirmedRoute: MainOrderOrderIdConfirmedRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
