// GENERATED by `npm run subscribers:generate`. Do not edit — your change will be overwritten.
//
// Every subscriber `src/subscribers/` defines, as static imports, so the handler closures exist in
// the process that dispatches and `tsx --watch` has a module graph to reload from. `npm run verify`
// fails when this file drifts from the source tree.
//
// `defineSubscriber` is called here rather than in each subscriber file: it is what erases the
// config's event type argument so subscribers of different event unions can share one list, and a
// subscriber file is meant to be a function plus a plain object, exactly like a job.

import { defineSubscriber, type SubscriberDefinition } from '../core/event-bus/types.js'
import { config as busProbe } from './bus-probe.js'
import { config as sendOrderConfirmation } from './send-order-confirmation.js'

export const GENERATED_SUBSCRIBERS: SubscriberDefinition[] = [
  defineSubscriber(busProbe),
  defineSubscriber(sendOrderConfirmation),
]
