// GENERATED by `pnpm --filter backend run jobs:generate`. Do not edit — your change will be overwritten.
//
// Every job `src/jobs/` defines, as static imports, so the handler closures exist in the cron
// Worker and `tsx --watch` has a module graph to reload from. `pnpm verify` fails when this file
// drifts from the source tree.
//
// It is also the *desired state* the cron Worker reconciles Temporal Schedules against: a job here
// gets a schedule, and a `cron_`-prefixed schedule no entry here names is deleted. Both runtimes
// read this one list — node through the cron Worker, workerd through its scheduled handler.

import type { JobDefinition } from '../core/types/scheduler.js'
import { config as heartbeat } from './heartbeat.js'

export const GENERATED_JOBS: JobDefinition[] = [
  heartbeat,
]
